### ISSUE TITLE
One should be able to exclude _id while includes are present in projection

### ISSUE THREAD

**Issue by winfinit** [mccormicka/Mockgoose#101]
getting an error when adding projection with includes and excluding _id

```javascript
Model.findOne({userName: userName}, "userName -_id", function(err, res) {
    console.log(err);
 // ...
}

// { [MongoError: You cannot currently mix including and excluding fields. Contact us if this is an issue.] name: 'MongoError' }
```

>A projection cannot contain both include and exclude specifications, except for the exclusion of the _id field. In projections that explicitly include fields, the _id field is the only field that you can explicitly exclude.
> http://docs.mongodb.org/manual/reference/method/db.collection.find/#db.collection.find

**Comment by ben-vdrop** [comment]
This fix has proved useful to us, can this be merged into the project?

**Comment by winfinit** [comment]
merged
