### ISSUE TITLE
Greater than and less than comparisons do not support dot notation.

### ISSUE THREAD

**Issue by seansullivan** [mccormicka/Mockgoose#106]
If value for comparison is contained within a subdocument such as:

```
days: {
    monday: {
        totals: 4
    }
}
```

You are unable to query this document using the dot notation `"days.monday.totals"`.

`db.orders.find({"days.monday.totals": {$gte: 3}});`

Also does not work with $gt, $lt, or $lte. 

I noticed many of the other comparison operations lookup the property value using `utils.findProperty(model, options.queryItem);` rather than `model[options.queryItem]` that is found in these comparison.

**Comment by winfinit** [comment]
i see that your changes were merged in already, does this require any more action?

**Comment by seansullivan** [comment]
Changes to address this issue live on this branch in my fork: https://github.com/seansullivan/Mockgoose/commits/ISSUE-106/convert-dot-notation-lookups-to-objects

If you notice via my commits, I had to make numerous changes to core lib/utils.js to address performing queries on deeply nested queries.  I am willing to work with you on getting these merged in, but due to the invasiveness of the changes I withdrew the pull request I had opened to deal with this issue (#106).

**Comment by winfinit** [comment]
this is now supported with 5.0 release, since it took different approach
