### ISSUE TITLE
$in not Working with RegExp

### ISSUE THREAD

**Issue by TommaHawk** [mccormicka/Mockgoose#110]
Hi,

I currently try to Filter an find using $in operator and RegExp. 
the following Testcase (added to test/operations/comparision/InOperation.spec.js) should succeed

           it('should be able to find a model $in using Array', function (done) {
                AccountModel.create(
                    {email: 'multiples@valid.com', password: 'password', values: ['one', 'two']},
                    {email: 'multiples@invalid.com', password: 'password', values: ['two', 'three']},
                    function () {
                        AccountModel.findOne({email: {$in: [/invalid/i]}}, function (err, result) {
                            expect(result).toBeDefined();
                            expect(result).not.toBeNull();
                            if (result) {
                                expect(result.values[1]).toBe('three');
                                done(err);
                            } else {
                                done('Error finding model');
                            }
                        });
                    });
            });

I can also add more testcases if helpful.

**Comment by winfinit** [comment]
https://github.com/mccormicka/Mockgoose/commit/03bc53b02194cdb47a8fe369075d5ab554eac2c9 was merged
