### ISSUE TITLE
Project gone stale?

### ISSUE THREAD

**Issue by duro** [mccormicka/Mockgoose#112]
No merged PRs or commit since September. 24 open issues and 15 open PRs. Is this project still moving forward? Evaluating using it with a new app, and I'm wondering if it's worth it?

**Comment by joeltello** [comment]
+1

**Comment by agconti** [comment]
+1

**Comment by legomind** [comment]
Same question here.

**Comment by tusharmath** [comment]
+1

**Comment by ruairitobrien** [comment]
+1

**Comment by deltaflux** [comment]
Same here. I've already had to fix several bugs in Mockgoose and wondering whether it's persevering with.

**Comment by SimenB** [comment]
@mccormicka Could you weigh in here?

**Comment by winfinit** [comment]
Hello, I am going to try to help out Anthony with merging your requests, be the end of this week, i will try to merge all legit pull requests.

thank you.
