### ISSUE TITLE
Query multiple levels deep

### ISSUE THREAD

**Issue by larron** [mccormicka/Mockgoose#114]
I've got a schema that looks like:

    schema.add({
        email_addresses: [
            {
                email_address: {type: String, unique: unique},
                primary: Date,
                verification: {
                    date: Date,
                    code: String,
                    code_expiration: Date
                }
            }
        ]
    });

Attempting to query with something three levels deep like  Model.findOne('email_addresses.verification.code', function() ... ) seems to be broken.

I have verified that this works with Mongoose / MongoDB

**Comment by winfinit** [comment]
this should be supported with 5.0 release

**Comment by larron** [comment]
Awesome, great news!  Thanks @winfinit
