### ISSUE TITLE
exec Promise support

### ISSUE THREAD

**Issue by albertorestifo** [mccormicka/Mockgoose#118]
Promises are the future. Mongoose supports them trough the `exec()` option

**Comment by winfinit** [comment]
Mockgoose has several examples in its unit tests with ```exec()```

**Comment by albertorestifo** [comment]
It's nowhere to be seen in the `README.md` any mention to the `exec` method.

The documentation in quite poor, at leas do mention in the `README` that you can look at the tests for some examples, maybe linking the best ones to look at
