### ISSUE TITLE
[regression 2.0.2] _id fields (ObjectID) got lost - broke our tests

### ISSUE THREAD

**Issue by Lekensteyn** [mccormicka/Mockgoose#120]
Heads-up: a "minor" update from 2.0.1 to 2.0.2 broke some of our tests. Reverting 9d9cd6898c5f545df979e63515e277e5f7607ace fixes the bug.

The error we get is:

    CastError: Cast to ObjectID failed for value "{ passwordHash: '...', email: 'foo@example.com', __v: 0 }" at path "user"

User is defined as this schema:
```js
{
  email: {
    type: mongoose.SchemaTypes.Email,
    required: true,
    index: { unique: true },
  },
  passwordHash: String
}
```

while the Session referring this User is:
```js
{
  user: {
    type: Schema.Types.ObjectId,
    ref: 'User',
  },
  // ...
}
```

Reporting this with (vague) details just in case you have an "aha!" moment. Let me know if you need more details.

These are the complete changes between 2.0.1 and 2.0.2:

```diff
diff -Nur 2.0.1/lib/Collection.js 2.0.2/lib/Collection.js
--- 2.0.1/lib/Collection.js	2015-04-18 18:32:10.000000000 +0200
+++ 2.0.2/lib/Collection.js	2015-04-19 05:32:58.000000000 +0200
@@ -112,12 +112,13 @@
         }
         validation.validate(name, obj, schema, function(err){
             if(err){
-                return callback(err);
+	            process.nextTick(callback.bind(null, err));
+	            return;
             }
             db[name][obj._id] = obj;
             logOptions(options);
             obj = Array.isArray(obj) ? obj : [obj]; 
-            callback(null, obj);
+	    process.nextTick(callback.bind(null, null, obj));
         });
     };
 
diff -Nur 2.0.1/lib/options/Filter.js 2.0.2/lib/options/Filter.js
--- 2.0.1/lib/options/Filter.js	2015-04-16 04:50:17.000000000 +0200
+++ 2.0.2/lib/options/Filter.js	2015-05-23 17:45:02.000000000 +0200
@@ -6,10 +6,13 @@
 module.exports = function filterFields(fields, results) {
     var includes = [];
     var excludes = [];
+    var projections = {};
     if (fields) {
         if (_.isObject(fields)) {
             _.forIn(fields, function (value, key) {
-                if (!!value ) {
+                if (_.isObject(value)) {
+                    projections[key] = value;
+                } else if (!!value ) {
                     includes.push(key);
                 } else {
                     excludes.push(key);
@@ -27,11 +30,38 @@
             throw new Error('Fields must be a string or an object!');
         }
     }
+    var error;
     if(includes.length && excludes.length && ( excludes.length > 1 || excludes[0] !== '_id' )  ){
-        var error = new Error('You cannot currently mix including and excluding fields. Contact us if this is an issue.');
+        error = new Error('You cannot currently mix including and excluding fields. Contact us if this is an issue.');
         error.name = 'MongoError';
         return error;
     }
+    var hasProjections = Object.keys(projections).length;
+    if (hasProjections && (includes.length || excludes.length)) {
+        error = new Error('You cannot currently mix projections and including or excluding fields. Contact us if this is an issue.');
+        error.name = 'MongoError';
+        return error;
+    }
+
+    if (hasProjections) {
+        _.forEach(results, function(result) {
+            _.forIn(projections, function(value, key) {
+                if (value.$slice) {
+                    if (_.isArray(value.$slice)) {
+                        result[key] = result[key].slice(value.$slice[0], value.$slice[1]);
+                    } else {
+                        result[key] = result[key].slice(value.$slice);
+                    }
+                } else if (value.$) {
+                    result[key] = result[key][0];
+                }
+            });
+
+        });
+        if (error) {
+            return error;
+        }
+    }
 
     if (includes.length || excludes.length) {
         results = _.map(results, function (result) {
diff -Nur 2.0.1/lib/utils.js 2.0.2/lib/utils.js
--- 2.0.1/lib/utils.js	2015-04-18 18:32:10.000000000 +0200
+++ 2.0.2/lib/utils.js	2015-05-23 17:45:02.000000000 +0200
@@ -160,12 +160,12 @@
 }
 
 function cloneItem(item) {
-    // Do not clone items that are ObjectId objects as _.clone() mangles them
-    if(item instanceof ObjectId) {
-        return item;
-    }
-
-    return _.clone(item);
+    return _.cloneDeep(item, function(value) {
+        // Do not clone items that are ObjectId objects as _.clone mangles them
+        if (value instanceof ObjectId) {
+            return new ObjectId(value.toString());
+        }
+    });
 }
 
 function isNestedKey(key) {
diff -Nur 2.0.1/package.json 2.0.2/package.json
--- 2.0.1/package.json	2015-04-18 18:32:10.000000000 +0200
+++ 2.0.2/package.json	2015-05-23 17:46:48.000000000 +0200
@@ -1,7 +1,7 @@
 {
   "name": "mockgoose",
   "description": "Mockgoose is an in memory database mock to allow for testing of applications that rely on Mongoose.",
-  "version": "2.0.1",
+  "version": "2.0.2",
   "author": {
     "name": "Anthony McCormick",
     "email": "anthony.mccormick AT gmail.com"
```

**Comment by Lekensteyn** [comment]
In the debugger on `cloneItem(item)` (utils.js) I see this:
```
item: Object
    __v: 0
    _id: ObjectID
        _bsontype: "ObjectID"
        id: "Ude-^X{^y®",\
        __proto__: ObjectID
    email: "foo@example.com"
    passwordHash: "pbkdf2:sha51..."
    __proto__: Object
```

value (`=item._id`) is however not instanceof ObjectId (`=require('mongodb').ObjectID`) and for some reason this `_id` field does not end up in the cloned object.

mockgoose uses mongoose 3.8.25 while our project uses mongoose 4.0.3, could this be an issue? Anyway, this "fixes" the issue for me, though I am not sure how appropriate it is:
```diff
diff --git a/lib/utils.js b/lib/utils.js
index 6f4d680..171cc3b 100644
--- a/lib/utils.js
+++ b/lib/utils.js
@@ -162,7 +162,7 @@ function cloneItems(items) {
 function cloneItem(item) {
     return _.cloneDeep(item, function(value) {
         // Do not clone items that are ObjectId objects as _.clone mangles them
-        if (value instanceof ObjectId) {
+        if (value.constructor && value.constructor.name === 'ObjectID') {
             return new ObjectId(value.toString());
         }
     });
```

**Comment by timmyg** [comment]
Yea, version 2.0.2 screwed up a ton of our tests. Was creating with _id but then findOne would return without _id

**Comment by alex94puchades** [comment]
Seems I am having this same problem with mockgoose 2.0.3, do you need any help reproducing this bug?

**Comment by alex94puchades** [comment]
Ok, I'm trying to track down this bug. At this moment, the error seems to be in the model passed to ```completeMany``` (mongoose/lib/query.js:1079), which is used in (mongoose/lib/queryhelpers.js:66) to instantiate an object whose init method is called, which invokes the callback at mongoose/lib/query.js:1088 with the missing fields. If someone knows where is the implementation of this init method, I think we could address this bug rather easily.

**Comment by alex94puchades** [comment]
This bug is now one month old. It has received so far no response from @mccormicka or any other mockgoose developer. Zero answers given. Absolutely no support for such an easy to reproduce bug. Of how much value is a mocking library that makes all the tests to fail? Personally, I'll be removing mockgoose from all my project dependencies, and I'll advise others to do the same. I hope the situation changes someday, but this is how things are now.

**Comment by winfinit** [comment]
Alex,

this is an open source project, pull requests are always welcome. contributors do see your complaint, but unfortunately i didn't get to research this issue yet, I am hoping that someone else can get to it before ill find a time, i was planning to do that sometime this weekend, but no guarantees.

**Comment by alex94puchades** [comment]
@winfinit I know, this bug has been driving me mad also. Which is understandable because I don't get to deal with mongoose/mockgoose internals on a daily basis. But a lot of my projects can't be tested properly because of this bug, and some people depend on them. This decision has not been driven by personal feelings, but by what I think it's the best decision, at least for now. I sincerely want this situation to improve. If help is needed I'll be glad to help. And if with this "rant" I get more people to focus on this (severe) bug, I'll be satisfied.

**Comment by winfinit** [comment]
just tried to update mongoose to version 4, and sure enough, as Lekensteyn said, i am getting about 30 failed tests with version 4.

**Comment by winfinit** [comment]
further looking at mongoose migration path, there are quite a few differences, one being on findAndModify and one of it being "new" option default value is now matching new MongoDBs defaults.

ones ill be fixing behavior for version 4, i will break version 3, and even if it won't seem like it is broken, i.e.: your tests will be passing, those will be bad tests, because now Mockgoose will get into "making your tests pass" as appose to "mocking real behavior".

in this case i feel what needs to happen is a new version of Mockgoose, I am thinking to match version of mongoose, i.e.: version 4 of mockgoose will support version 4 of mongoose, and i will up the version to 3 of mockgoose version 3, and leave 2 at legacy release, that way you will decide what dependency to include... that would also mean that i would have to maintain 2 releases most likely.

**Comment by developit** [comment]
We're getting bit by this too. Is it possible this year-old commit solves the issue?
c781b41ef0a6d950e1b4ae57be0e5e778235eaba

It seems to be an attempt to add Mongoose 3.8 compatibility, and provides an alternative to the instanceof ObjectId check mentioned above?

**Comment by whummer** [comment]
+1 same problem here

**Comment by winfinit** [comment]
please update to 5.0 release, and let me know if you are experiencing any problems
