### ISSUE TITLE
Problem with Mongoose 4.x

### ISSUE THREAD

**Issue by tamlyn** [mccormicka/Mockgoose#125]
My project is using the latest stable Mongoose: 4.0.5. 

Mockgoose requires `"mongoose": "^3.8.25"` which causes npm to install a separate copy of mongoose under `node_modules/mockgoose/node_modules/mongoose`. This in turn causes code in Mockgoose such as `if (value instanceof ObjectId)` (from `utils.js`) to fail since `ObjectId` in Mockgoose is not the same object as `ObjectId` in my main project.

It seems to me that Mockgoose shouldn't have Mongoose in its `dependencies` at all. Mockgoose should **always** use the copy of Mongoose from the parent project and if the parent project does not have Mongoose then it should fail. 

Moving Mongoose to `devDependencies` should be fine as these are not installed in a required module by default.

In the meantime here is a workaround:

1. `npm uninstall -S mongoose mockgoose`
2. `npm install -S mongoose@~3.8 mockgoose`

This locks you to Mongoose 3.8.x (avoiding the unstable 3.9 branch) while ensuring that only one copy of Mongoose is installed.

**Comment by arnaugm** [comment]
Agree

**Comment by schmittyjd** [comment]
We should be able to use Mongoose 4.x though

**Comment by alex94puchades** [comment]
I agree with @tamlyn. This is already causing bugs (see #120).

> if the parent project does not have Mongoose then it should fail.

Mockgoose constructor requires an instance of mongoose, so it shouldn't be a problem.

**Comment by zxqfox** [comment]
Bad news everyone.
With mongoose 4.1.2:
```
  187 passing (49s)
  64 failing
```
