### ISSUE TITLE
MongoError: mock: connect failed

### ISSUE THREAD

**Issue by revanthreddy** [mccormicka/Mockgoose#126]
I am trying to execute the below mocha test but I send getting the "MongoError: mock: connect failed" error.

```javascript

var assert = require("assert");
var mongoose = require('mongoose');
var mockgoose = require('mockgoose');
mockgoose(mongoose);
var Item = require('../models/Item');

// create mock models using data we can count on
beforeEach(function (done) {
    mockgoose.reset();
    
Item.create({
        "_id": "1",
        "sg": "sg-xxxxxy"
    }, function (err, model) {
        if(err)
            done(err);
        else{
            console.log("item : "+model);
            done();
        
        }
    });

});

afterEach(function (done) {
    //Reset the database after every test.
    mockgoose.reset();
    done();
});

describe('Find a crio', function () {
    describe('#find()', function () {
        it('should be asynchronous', function(done) {
            var sg = "sg-xxxxxy";
       Item.findOne({"sg" : sg}).exec(function(err , doc){
                console.log(err);
                if(err)
                    done(err);
                assert.equal(sg, doc.sg);
                done();
            });
        });

    });
});
```

FYI : I am new to mongoose and mockgoose so any best practice tips are appreciated

Thanks,
Revanth

**Comment by winfinit** [comment]
I would suggest to look at existing tests of Mockgoose as a reference, check this directory out:
https://github.com/mccormicka/Mockgoose/tree/master/test

**Comment by revanthreddy** [comment]
That helped .. thanks !!

**Comment by juanpabloaj** [comment]
@revanthreddy how you can solve your problem ? I have the same

**Comment by winfinit** [comment]
@juanpabloaj please see tests directory, for example this test: https://github.com/mccormicka/Mockgoose/blob/master/test/Find.spec.js shows you how to structure your test, perform connect, create and find created document, it also utilizes before each and after each hooks.

**Comment by juanpabloaj** [comment]
@winfinit yes, I checked the tests directory, but my problem was other ...

first I used mongoose 4.0.4 ... when I change to ~3.8 every work fine, thanks.
