### ISSUE TITLE
Error: Cannot find module 'mongodb/node_modules/bson'

### ISSUE THREAD

**Issue by nottinhill** [mccormicka/Mockgoose#128]
Hi there - I am getting this error when running mockgoose in my karma project:

    module.js:340
        throw err;
        ^
    Error: Cannot find module 'mongodb/node_modules/bson'
      at Function.Module._resolveFilename (module.js:338:15)
      at Function.Module._load (module.js:280:25)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at Object.<anonymous>         
    (/Users/user/devel/app/node_modules/mockgoose/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:8:16)

Could you fix this? As we cant expect everyone to have mongodb installed as a npm module?

**Comment by depoulo** [comment]
I'm having the same error when using npm@3.1.1. I'm guessing mockgoose is trying to be clever by requiring modules out of the mongodb folder, which fails with npm@3's new "flat dependencies" approach.

**Comment by nottinhill** [comment]
Any workaround ideas? For the time being we stopped using Mockgoose and test against a Test DB.

**Comment by depoulo** [comment]
I don't have this issue with npm@2, and npm@3 is still in beta...

**Comment by wmertens** [comment]
npm v3 expects peer dependencies to be required by the project, not the library. So if I'm understanding right, you need to add mongodb to the requirements of your project @nottinhill.

**Comment by winfinit** [comment]
in 5.0 this was removed.
