### ISSUE TITLE
On upsert, _id use wrong ObjectId class

### ISSUE THREAD

**Issue by godu** [mccormicka/Mockgoose#131]
1. I insert document with `Model.update(conditions, update, {upsert: true})`.
*Mockgoose uses `mongodb.ObjectId` to set _id attribute.*

2. I want to update my document with `Model.update(conditions, update)`.
*On find command, Mockgoose clones result with `utils.cloneItem` and breaks _id type. `model._id.toString()` returns `[object Object]` instead of the hash. Mockgoose creates new entry `[object Object]` in collection's hash map*

**Comment by T1B0** [comment]
this commit https://github.com/mccormicka/Mockgoose/commit/a92789b76f579f85c451485fe14146c112a04f98 
reopen this bug, using process.env.PWD is a terrible idea that will go wrong and break a lot of use case, please revert it

**Comment by winfinit** [comment]
this should not be an issue with 5.0.
