### ISSUE TITLE
[MongoError: mock: connect failed] name: 'MongoError', code: 13328

### ISSUE THREAD

**Issue by PreethiBabu87** [mccormicka/Mockgoose#140]
Hi 

I want to use Mockgoose to test the mongoose save actions in my controller.
But I get the below error :
[MongoError: mock: connect failed] name: 'MongoError', code: 13328
Am stuck with this issue for a week. Kindly help to fix this.

Below is the code:

Test\SharePointInfo.js
-----------------------
var mockgoose = require('mockgoose');
var mongoose = require('mongoose');
var expect = require('expect.js');

// mock mongoose before requiring the script which establishes the connection (to mock the connection)
mockgoose(mongoose);
var config = require('../config/config.js');
require('../config/DBConnection.js')(config);//mongoose connection

//var should = require('should');
//var assert = require('assert'),
//    _ = require('underscore');
var SharePointInfo = require('../app/models/SharePointInfo.js')
var SharePointActionsToTest = require('../app/controllers/SharePointInformation.js');

beforeEach(function (done) {
    mockgoose.reset();
    // create and insert two dummy docs
    SharePointInfo.create({
        Hostname: "testHost",
        Success : true,
        Errors: [],
        SharePoint2003: true,
        SharePoint2007: false,
        SharePoint2010: false,
        SharePoint2013: false,
        RegistryKeys: [{
                Key: "key123",
                IsFound: true,
                Value: "value123",
                RegistryView: "regView"
            }],
        ApertureDeviceBasicInfo: [{
                VobId : "123456",
                UniqueId : "45678",
                DeviceName : "testHost",
                SerialNumber : "INC3456",
                BarcodeNumber : "RR4567",
                Manufacturer : "TestMan",
                Model : "TestModel",
                AssetNumber : "TestAsset",
                DeviceType : "DummyDeviceType",
                Description : "desc",
                Building : "crest",
                Floor : "8",
                Platform : "Windows",
                Os : "windows",
                MachineCategory : "dummycatehory",
                MachineType : "dummymachnetype",
                StorageType : "storageType",
                BackupType : "backuptype",
                SystemType : "dummysysteype",
                InstallDate : "2012-10-15T21:26:17Z",
                Country : "US",
                HaClusterNode : "yes",
                Region : "NAM",
                Cluster : "NAMCluster",
                InstallStatus : "Active",
                UseStatus : "Active",
                SpaceId : "9999",
                GridLocation : "US",
                RackName : "RAck7890",
                BottomRackUnit : "Unit5678",
                ParentDeviceName: "testHost",
                RemsId : "89067",
                Fqdn : "6tyu876",
                ApertureSupportGroups: [{
                        VobId : "123456",
                        SupportGroupType : "appsupport",
                        SupportGroup : "ostsupportgroup",
                        GroupEmail : "ostsupportgroup",
                        GroupHotline : "osthotline",
                        GroupUrl : "ost.nam",
                        PrimaryContactSoeId : "pm18094",
                        SecondaryContactSoeId : "pm18094"
                    }]
            }]
    }, function (err, model) {
        done(err);
    });
});

afterEach(function (done) {
    //Reset the database after every test.
    mockgoose.reset();
    done();
});

describe('SharePoints', function () {
    describe('GetAllRecords', function () {
        it('SharePointInfo.find() should give 1 document back', function (done) {
            
            SharePointActionsToTest.GetAllSharepointInformation(function (result) {
                expect(result).to.equal(1);
                done();
            });
            
        });
    });
});

DBConnection.js
var mongoose = require('mongoose');
var getMessagesAndProcess = require('./GetMessagesFromQueue.js');
var mongoQueries = require('./QueryMongoDB.js');
mongoose.set('debug', true)
//connect to our database
//Ideally you will obtain DB details from a config file
module.exports = function (config) {
    var dbName = 'xxx';
    var result;
    var connectionString = config.DB.connectionString;
    console.log(connectionString);
    //mongoose.connect(connectionString);
    
    var options = {
        auth: { authSource: 'admin' },
        server: { ssl: true, sslValidate: false }
    }
    
    
    //var dbName = 'OST';
    //var connectionString = 'mongodb://vm-1b98-f53f.nam.nsroot.net:32017/OST';
    mongoose.connect(connectionString, options);
    
    mongoose.connection.on('connected', function (callback) {
        console.log('Mongoose default connection open to ' + connectionString);
        
        
    });
    
    mongoose.connection.on('error', function (err) {
        console.log('Mongoose default connection error: ' + err);
    });
    
    // When the connection is disconnected
    mongoose.connection.on('disconnected', function () {
        console.log('Mongoose default connection disconnected');
    });

    // If the Node process ends, close the Mongoose connection 
    process.on('SIGINT', function () {
        mongoose.connection.close(function () {
            console.log('Mongoose default connection disconnected through app termination');
            process.exit(0);
        });
    });
};

Controllers/SharePointInformation.js
---
var SharePointInfo = require('../models/SharePointInfo.js');
var logs = require('../../config/LogMessage.js');
exports.GetAllSharepointInformation = function GetSharepointInfo(callback) {
    SharePointInfo.find({}, function (err, spData) {
        if (err) {
            console.log(err);
        } else {
            //console.log(hosts);
            callback("", spData);
        }
    }); // end Host.find 
}

Models\SharePointInfo.js
---
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var ApertureDeviceBasicInfoSchema = new Schema(
    {
        //ApertureDeviceBasicInfoId: Number,
        VobId : String,
        UniqueId : String,
        DeviceName : String,
        SerialNumber : String,
        BarcodeNumber : String,
        Manufacturer : String,
        Model : String,
        AssetNumber : String,
        DeviceType : String,
        Description : String,
        Building : String,
        Floor : String,
        Platform : String,
        Os : String,
        MachineCategory : String,
        MachineType : String,
        StorageType : String,
        BackupType : String,
        SystemType : String,
        InstallDate : { type: Date, default: null },
        Country : String,
        HaClusterNode : String,
        Region : String,
        Cluster : String,
        InstallStatus : String,
        UseStatus : String,
        SpaceId : String,
        GridLocation : String,
        RackName : String,
        BottomRackUnit : String,
        ParentDeviceName: String,
        RemsId : String,
        Fqdn : String,
        ApertureSupportGroups: [{
                //ApertureSupportGroupId : Number,
                //ApertureDeviceBasicInfoId : Number,
                VobId : String,
                SupportGroupType : String,
                SupportGroup : String,
                GroupEmail : String,
                GroupHotline : String,
                GroupUrl : String,
                PrimaryContactSoeId : String,
                SecondaryContactSoeId : String,
                _id: false
            }]
    },
    { _id: false }
);

var SharePointSchema = new Schema(
    {
        Hostname: String,
        Success : Boolean,
        Errors: [{
                Hostname: String,
                Message: String,
                JobName: String,
                WorkerName: String,
                _id: false
            }],
        SharePoint2003: Boolean,
        SharePoint2007: Boolean,
        SharePoint2010: Boolean,
        SharePoint2013: Boolean,
        RegistryKeys: [{
                Key: String,
                IsFound: Boolean,
                Value: String,
                RegistryView: String,
                _id: false
            }],
        ApertureDeviceBasicInfo: [ApertureDeviceBasicInfoSchema]
    }, 
    {
        collection: 'SharePointInfo'
    }
);

module.exports = mongoose.model('ApertureDeviceBasicInfo', ApertureDeviceBasicInfoSchema);
module.exports = mongoose.model('SharePointInfo', SharePointSchema);

Thanks
Preethi

**Comment by winfinit** [comment]
this should not be an issue with 5.0
