### ISSUE TITLE
Data corruption

### ISSUE THREAD

**Issue by yuvalyn** [mccormicka/Mockgoose#151]
Hello,

I had strange results in my own project tests using mockgoose.
In order to check it I forked the project and added a test to IncOperation.spec.js (I had problems with the ```$inc``` parameter).

```javascript
it('Be able to increment a value multiple times', function (done) {
    IndexModel.findOneAndUpdate(
        {name: 'one'},
        {$inc: {value: 4}},
        {'new': true},
        function (err, res) {
            expect(res.value).to.equal(7);
            IndexModel.findOneAndUpdate(
                {name: 'one'},
                {$inc: {value: 2}},
                {'new': true},
                function (err, res) {
                    expect(res.value).to.equal(9);                            
                    done(err);
                }
            );
        }
    );
});
```

This test fails. It seems that the second time you update, the data is already corrupted. All other tests reset the data each time. I tried finding the problem myself but it was a bit hard for to get into the project code. From what I was able to find out, the problem is not with the "Increment" operation but somewhere else down the line.

**Comment by winfinit** [comment]
5.0 should not have same issues anymore, please report any other problems that you may run into
