### ISSUE TITLE
mockgoose don't know to query on array keys with in operator

### ISSUE THREAD

**Issue by jackpoll** [mccormicka/Mockgoose#155]
I've an array field in the DB, something like:

`db.things.insert({'type': 'Information', 'data':[{'key':1, name:'1'},{'key':2,'name':'2'}]})`
`db.things.insert({'type': 'Information', 'data':[{'key':3, name:'3'},{'key':4,'name':'4'}]})`

When trying to query:

`db.things.find({'data.key':{$in:[1,2]}})`
It doesn't work, outputting:
TypeError: Cannot read property 'key' of undefined  node_modules/mockgoose/lib/utils.js:233:22

But it works in mongoose. how can I fix that?

**Comment by winfinit** [comment]
@jackpoll I am currently working on a next release, currently it is rc, can you define mockgoose version "5.0.0-rc.10" and provide your feedback please?

**Comment by jackpoll** [comment]
I've tried, missing base functions, such as: mongoose.reset()

**Comment by fracmak** [comment]
There's a pull request restoring that functionality: #154

**Comment by winfinit** [comment]
just merged reset functionality mockgoose@5.0.0-rc.12

thank you!

**Comment by winfinit** [comment]
5.0 is now latest, closing this ticket
