### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by PavelVanecek** [mccormicka/Mockgoose#156]
I can see that mockgoose recently progressed from version 4 to 5 using a different approach. Deep down in issue comments and commit messaged I found mentions of using real database instead of mocking. Does it change the way the library is used? Does it add new features? Remove features? Change behaviour in any way? Is migration recommended?

The major version bump in [semver](http://semver.org/) means "API incompatible breaking changes." Which are the breaking changes? What is the migration guide, if any?

I am missing a `CHANGELOG.md` file that would answer all these questions on one place, as opposed to browsing dozens of commits and source code changes.

**Comment by winfinit** [comment]
@PavelVanecek I am not following semver specification, but rather major.minor.patch versioning, where going from 4 to 5, means that there are core changes in the library, 

I do like your change log proposal, and will incorporate that.

Library is using now real mongod process, with in memory storage, and not focused anymore on replicating storage engine behavior, or duplication mongoose functionality. New versions goal is to provide a storage facility without tester knowing nor caring on how it is done, but just know that tests are executed against mongod without one explicitly starting or managing separate process.

**Comment by winfinit** [comment]
changelog is being added starting with current release, thank you so much for your input.
