### ISSUE TITLE
Mockgoose failure when making connection in Mocha tests of Express

### ISSUE THREAD

**Issue by rlamorea** [mccormicka/Mockgoose#158]
I updated to the latest Mockgoose and my tests no longer complete.
The Mockgoose connection is failing.  The failure is:

     TypeError: Cannot set property '0' of undefined
         at EventEmitter.<anonymous> (.../node_modules/mockgoose/Mockgoose.js:30:25)
         at EventEmitter.g (events.js:199:16)
         at EventEmitter.emit (events.js:129:20)
         at EventEmitter.<anonymous> (.../node_modules/mockgoose/Mockgoose.js:71:25)
         at EventEmitter.g (events.js:199:16)
         at EventEmitter.emit (events.js:104:17)
         at Socket.<anonymous> (.../node_modules/mockgoose/node_modules/mongodb-prebuilt/index.js:67:14)
         at Socket.emit (events.js:107:17)
         at readableAddChunk (_stream_readable.js:163:16)
         at Socket.Readable.push (_stream_readable.js:126:10)
         at Pipe.onread (net.js:538:20)

The failure seems to happen because this handler, on line 22 of Mockgoose.js is being called twice.  This first time, connect_args is defined and all is well.  The second time, connect_args is not defined and it fails.

     emitter.once("mongodbStarted", function(db_opts) {
        connect_args[0] = "mongodb://localhost:" + db_opts.port;
        debug("connecting to %s", connect_args[0]);
        orig_connect.apply(mongoose, connect_args);
    });

My tests start as follows:

     var mockgoose = require('mockgoose');
     mockgoose(mongoose);
     var app = require('../app.js');

The mongoose connect is done in the instantiation of the app.  This worked fine prior to the upgrade of Mockgoose.

I am also doing a Mockgoose.reset() in the mocha `before` handler.

**Comment by winfinit** [comment]
@rlamorea can you please share how connection is done in your app?

**Comment by rlamorea** [comment]
Not doing anything strange.  Basically, in app.js -

     var mongoUrl = "mongodb://" + config.database.mongo.host + ':' + config.database.mongo.port + '/' + config.database.mongo.dbname;
     mongoose.connect(mongoUrl, function(err) { /* error handling */ });

The connect is wrapped in some retry code, but the failure happens on the first try.

In the meantime I downgraded Mockgoose to 4.0.2 and things work again.

**Comment by chiulam** [comment]
You can verify if the mockgoose is already mocked by 
```javascript
if (mockgoose.hasOwnProperty('reset')) {
	// mocked
} else {
	// mock it now
	mockgoose(mongoose);
}
```
But I prefer Mockgoose to have a `unmock` method so we can run it in `after`.

In https://github.com/mccormicka/Mockgoose/issues/62, someone did it by 
```
    afterAll(function() {
        delete require.cache[require.resolve('mongoose')];
    });
```

**Comment by winfinit** [comment]
@chiulam just added unmock method, and instance variable isMocked in 5.1.0

@rlamorea in your app.js, do you have something like this? 
```javascript
var Mongoose = require('mongoose').Mongoose;
var mongoose = new Mongoose();

var mongoUrl = "mongodb://example.com:27017/foobar";
mongoose.connect(mongoUrl, function(err) { });
//...
```

and in your test, something similar to this?
```javascript
var Mongoose = require('mongoose').Mongoose;
var mongoose = new Mongoose();
var mockgoose = require('mockgoose');
mockgoose(mongoose);
var app = require('./app.js');
// ...
```

**Comment by rlamorea** [comment]
Sorry for the late reply.  I haven't been able to get back to this until now.
But yes, that is exactly what I've got.

**Comment by rlamorea** [comment]
Ok, I found the "problem", and it was how I was setting up and running tests.

Each of my tests was creating an "app" instance, and due to concurrency these multiple apps were creating multiple mockgoose connections.  The first one worked, but subsequent ones failed.

The solution was to create a mocha bootstrap file that creates the app and mockgoose one time for all the tests.  For completeness, here was my bootstrap for mocha:

     // _bootstrap.js
before(function(done) {
         var mongoose = require('mongoose');
         var mockgoose = require('mockgoose');
         mockgoose(mongoose);

         var app = require('../app.js');
         app.get('config').services.cookiedomain = null; // reset this
         // stick these on global in case I need to use them in other tests
         global.mockgoose = mockgoose;
         global.app = app;
         done();
     });

Closing out the issue.

**Comment by ektachawla** [comment]
Hi,
I am having similar issue. Need to setup connection etc only once, before all the unit tests are executed in different files, So i have created a _bootstrap.js file which does the initialisation. However, by the time initialisation completes, tests already start executing and since global variables are not set, all start failing. I tried by putting describe() inside setTimeout(), but that doesnot work either. Can someone please suggest on this.
Thanks
