### ISSUE TITLE
update returning same document as before

### ISSUE THREAD

**Issue by franky-continu** [mccormicka/Mockgoose#160]
Hi all my update tests are failing after removing local mongodb creation and going with mockgoose. I use Mockgoose in a lot of other projects but this is the first time I ran into this issue:

I have this mocha test (supertest, should, etc)

```javascript
it('should be able to update a venue', function(done){
    var data = {
      name: 'Fillmore Theater'
    };
    request(url)
      .post('/common/venues/'+ venueId +'?access_key=' + companyAccessKey)
      .send(data)
      .end(function(err, res){
        if(err) { console.log(err); }
        venueId = res.body._id;
        res.status.should.be.equal(200);
        res.body.should.have.property('name', 'Fillmore Theater');
        res.body.should.have.property('address_line_1');
        res.body.should.have.property('city');
        res.body.should.have.property('state');
        res.body.should.have.property('zip_code');
        res.body.should.have.property('country')
        done();
      });
  });
```

And the code updates like this:

```javascript
exports.update = function (req, res, next){
  req.accepts('json');
  var query = { _id: req.params.id, company: req.companyId };
  Venue.findOneAndUpdate(query, {$set: req.body }, function(err, venue){
    if(err) {
      res.json(422, err);
      return next();
    }
    res.json(200, venue);
    return next();
  });
};
```

**Comment by winfinit** [comment]
@franky-continu what release of mockgoose are you using?

**Comment by franky-continu** [comment]
5.0.4 I believe that the error comes from mongodb-download

**Comment by franky-continu** [comment]
https://github.com/winfinit/mongodb-download/issues/5

**Comment by franky-continu** [comment]
I’ve been battling 2 days with an old api that I upgraded and wanted to lunch it through docker and tutum.

We have successfully migrated all our stack, except this api. I cleaned it, upgrade it, replace a bunch of code and everything runs awesome.

But my Docker build was failing and I just found out why - or sort of.

Mockgoose depends on mongoldb-prebuilt which depends on mongoldb-download which throws an error on the docker image for debian 8.2.
/usr/src/app/node_modules/mongodb-download/index.js:127
throw new Error("unsupported release of Debian " + os.release);
^
Error: unsupported release of Debian 8.2`

I’m not sure how can I solve this issue, so I’m checking up with you to get some pointers or help.

**Comment by winfinit** [comment]
@franky-continu sorry for a delay, I am currently setting myself up with debian, and will keep you posted on a progress. I am hoping that provided version of mongodb for wheezy will also work with jessie, otherwise I will have to look for alternative method that will work in this instance.

**Comment by winfinit** [comment]
@franky-continu please try 5.0.5

**Comment by franky-continu** [comment]
5.0.5's dependencies (mongodb-pebuilt -> mongodb-download) is working for Debian 8.2.

This issue got sidetracked, so I'll close it.
Thanks a bunch Roman
