### ISSUE TITLE
Reset errors

### ISSUE THREAD

**Issue by mindmelting** [mccormicka/Mockgoose#166]
Hello

This PR https://github.com/mccormicka/Mockgoose/pull/163 seems to have broken `reset` for me, and now errors with:

```
collections.forEach is not a function
```

Reverting to version 5.0.6 and back to using the async lib, fixes this...

I'll have a quick look into it, but I assume this may be a mongo specific implementation of forEach on collections which is not present when I do a fresh `npm install`

**Comment by mindmelting** [comment]
See failing test here: https://github.com/mindmelting/Mockgoose/commit/936a14e7a60ba0bafb3a500d92d681d327cea169

**Comment by ppitonak** [comment]
I can reproduce this. It is somehow related to issue #158... when I have only one file with test, I get this error, when I add another file with tests where I use Mockgoose, I get error as described in issue #158.

**Comment by winfinit** [comment]
as always, thank you for reporting this issue, @mindmelting i've updated test to your test, and with most recent version of mockgoose, it is passing now.

mockgoose@5.0.11
