### ISSUE TITLE
Documentation for mockgoose.reset

### ISSUE THREAD

**Issue by weeksling** [mccormicka/Mockgoose#168]
Was there not previously documentation on how to use mockgoose.reset for database teardown? This was rather useful before, was it removed for a reason?

**Comment by winfinit** [comment]
@weeksling I will update docs, however it was removed for a reason, because i wanted mockgoose just to handle methods that are absolutely required, and are part of mongoose, and reset is not part of mongoose, but due to demand, this helper method is added back.

**Comment by winfinit** [comment]
added in mockgoose@5.0.11, thank you for your input.
