### ISSUE TITLE
Regression, exception calling .reset()

### ISSUE THREAD

**Issue by gaggle** [mccormicka/Mockgoose#169]
Using `^5.0.10` I encountered a regression on calling `mockgoose.reset()`. It threw an exception.
Downgrading to `^4.0.1` fixed the problem.

**Comment by winfinit** [comment]
@gaggle there was an issue with reset, plus additional request to add unmock method, both of those were addressed in 5.1.0

**Comment by gaggle** [comment]
Oh, didn't know I was behind. Cheers.
