### ISSUE TITLE
Mockgoose fails if MongoDB is running on port 27017

### ISSUE THREAD

**Issue by awochna** [mccormicka/Mockgoose#171]
I'm writing Mocha test for an application and using mockgoose to handle the testing datastore. The tests were originally just using a regular mongo database before I ran into mockgoose and at that point they were passing. Once I started using mockgoose, my tests started timing out (2000ms default in mocha), so I started doing some playing in the node REPL.

## The background ##

I have tested this behavior on my desktop and a virtual machine on my desktop, both running Ubuntu 14.04 and Mongo 3.0.8. The desktop is using node 5.3.0 and the virtual machine is using node 4.2.3.

## The experiments ##

It seemed like the order of calls could be important so I tried the following:

* Not requiring mockgoose at all and not calling connect on mongoose. Mongoose reports no connection (host/port = null; expected).
* Not requiring mockgoose and calling connect on mongoose. Mongoose reports a connection (expected). Documents can be persisted, but they are stored on disk.
* Requiring mockgoose, not calling `mockgoose(mongoose);`, and calling connect on mongoose. Same as previous bullet.
* Requiring mockgoose, calling `mockgoose(mongoose);`, and then calling connect on mongoose. Mongoose reports no connection, the callback passed is never run, tests time out even if the timeout is raised. Mongoose reports that it is mocked. This also happens if no explicit call to connect is made.
* Requiring mockgoose, calling connect on mongoose, and then calling `mockgoose(mongoose);`. Mongoose reports a connection and that it is mocked, but documents trying to be persisted get stored on disk. I would consider this unexpected behavior.

## The problem ##

Trying to use mockgoose as specified and connect to an in-memory database fails. I don't know how to debug or diagnose further.

Additionally, if mongoose is already connected and mockgoose is passed that instance of mongoose later, it reports both that it is connected and mocked, but it is connected to an on-disk database. Ideally, I would expect that it should disconnect the mongoose instance and reconnect to the in-memory database.

I'm sorry I couldn't find out more. Let me know if there is more information I can give.

# Update 2016-01-08 #

I've debugged this further and found it to be a conflict with the fact that the default port is already in use. It *looks like* there is code to handle this error and increment the port number until an open port is found. Unfortunately, it does not seem to be working.

I have forked the repo and added MongoDB to the CI settings and confirmed it fails in Travis. You can view the settings [here](https://github.com/awochna/Mockgoose/blob/master/.travis.yml) and the failing job output [here](https://travis-ci.org/awochna/Mockgoose/jobs/101102301).

I haven't yet wrapped my head around where this problem is coming from, Mockgoose or mongo-prebuilt. It looks like mongo-prebuilt should return an error to the callback in this case, but if an error was being returned, Mockgoose should increment the port number. I'll look into debugging this occasionally as time permits.

## If you have this problem ##

In the meantime, if you are encountering this issue, you can stop your current mongod process or pass an options object to mockgoose when you call `mockgoose(mongoose);` and specify some silly port number that you're sure isn't taken:

    mockgoose(mongoose, { port: 654398 });

**Comment by DukeBaird** [comment]
Im having the same issue, my tests are timing out on my machine (Xubtuntu 14.04). 

The order that Im following is one of the ones that was listed: 
- Requiring mockgoose, calling mockgoose(mongoose);, and then calling connect on mongoose. Mongoose reports no connection, the callback passed is never run, tests time out even if the timeout is raised.

However, switching my port and killing my mongod process haven't helped.

**Comment by awochna** [comment]
@DukeBaird Interesting, perhaps it's not related to the port conflict. In my case, stopping mongod has allowed the tests to run. I haven't had a chance to test a different port yet.

**Comment by winfinit** [comment]
I will try to mess with it also, previously i was unable to duplicate this on my machine, but this is not the first time i hear about this behavior, so I will try harder to duplicate this. thank you for your update, report and investigation.

**Comment by cantremember** [comment]
this may be addressed as a side-effect of changes to #182 

i was running into the exact same issues.  thanks to [portfinder](https://github.com/indexzero/node-portfinder) they pass on my machine even with my `mongod` running locally on :27017

of course, YMMV, and those changes are not yet released, although they are in `master`

**Comment by daithi-coombes** [comment]
I can report the same issue:
```javascript
before(function(done){
  mongoose.connect($testEndpoint, function mongoMockCB(err){
    done(err)
  })
})
```
The function `mongoMockCB` callback never gets called, thus my unit test is timing out.

**Comment by daithi-coombes** [comment]
... none of the op's suggestions worked for me either:
```
//stopping mongod service
mockgoose(mongoose, { port: 654398 })
```

**Comment by winfinit** [comment]
i didn't release new version yet, but I am expecting this issue to be gone at this point. However, folks that are experiencing this bug, can you please add output to this thread of your minimal test case that can reproduces this issue with environment variable "**DEBUG=***" set

**Comment by halleycarleton** [comment]
I'm not sure if this is the same bug, but I'm having an issue where a mocked mongoose.connect call will timeout in a mocha `before()` but not anywhere else.

example:
```js
	before(function(done) {
		var spy = sinon.spy();

		mockgoose(mongoose);
		mongoose.connect('mongodb://localhost/testDB', spy);

		setTimeout(function() {
			console.log('spy has been called ' + spy.callCount + ' times.');
			done();
		}, 1800);
	});
```
` spy has been called 0 times`

but if I do the same in an `it()` it will be called:
```js
	it('should call callback', function() {
		var spy = sinon.spy();

		mockgoose(mongoose);
		mongoose.connect('mongodb://localhost/testDB', spy);

		setTimeout(function() {
			expect(spy.called).to.be.true;
		}, 1800);
	});
```
`Test Passed`

**Comment by winfinit** [comment]
please upgrade to most recent release, there is a breaking api change in 6.0.0, but after upgrade it would give me ability to address tons of quirkiness that people are being reporting.

**Comment by winfinit** [comment]
please reopen this issue, if you are still having a problem with 6.0.0

**Comment by putuyoga** [comment]
i am still having this problem with 6.0.8, `then()` callback never called.

`mockgoose(mongoose).then(() => {
    mongoose.createConnection(serverConfig.mongoURL, err => {
      if (err) t.fail('Unable to connect to test database');
      done();
    });
  });`
