### ISSUE TITLE
Mocha tests using Mockgoose will fail if mongodb-download can't download or mongodb-prebuilt can't fully decompress in time

### ISSUE THREAD

**Issue by welps** [mccormicka/Mockgoose#174]
If mongodb-download fails to download the package or mongodb-prebuilt fails to decompress the package completely in time, mocha tests will fail since the package doesn't exist or have all necessary files.

Further attempts to test on the same box may fail if mongodb-prebuilt manages to decompress partially due to mongodb-prebuilt's check whether the folder already exists. In this case, you need to wipe the `node_modules/mongodb-prebuilt/dist/mongodbversion` folder to have it try again.

An obvious workaround is to give enough time to complete via the mocha --timeout parameter, which I assume why this repo's test uses the timeout parameter, but this is unreliable since both stated operations (download/decompression) are variable.

Shouldn't mongodb-download's download and mongodb-prebuilt's decompression be set to block in this case since we depend on successful completion to proceed?

## Debug info:

**Mockgoose's npm test when download fails to complete in time**
```
DEBUG=* mocha test
  mocha:suite bail undefined +0ms
  mocha:suite enableTimeouts true +6ms
  mocha:suite bail undefined +10ms
  Mockgoose dbpath: /www/data/Mockgoose/.mongooseTempDB +0ms
  mocha:runnable timeout 2000 +720ms
  mocha:runnable enableTimeouts true +1ms
  mocha:runnable timeout 75 +0ms
  mocha:suite timeout 2000 +1ms
  mocha:suite enableTimeouts true +0ms
  mocha:suite slow 75 +0ms
  mocha:suite bail undefined +0ms
  mocha:runnable timeout 2000 +1ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable timeout 75 +0ms
  mocha:runnable timeout 2000 +1ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable timeout 75 +0ms
  mocha:runnable timeout 2000 +1ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable timeout 75 +0ms
  mocha:runnable timeout 2000 +0ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable timeout 75 +1ms
  mocha:runnable timeout 2000 +0ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable timeout 75 +0ms
  mocha:runnable timeout 2000 +0ms
  mocha:runnable enableTimeouts true +0ms
  mocha:runnable timeout 75 +0ms
  mocha:runner grep /.*/ +1ms
  mocha:runner globals ["global","process","GLOBAL","root","Buffer","clearImmediate","clearInterval","clearTimeout","setImmediate","setInterval","setTimeout","console","Reporter","before","after","beforeEach","afterEach","run","context","describe","xcontext","xdescribe","specify","it","xspecify","xit","XMLHttpRequest","Date","errno"] +2ms
  mocha:runner globals [] +1ms
  mocha:runner start +0ms

  mocha:runner run suite  +1ms

  Mockgoose attempting to start server on port: 27017 +18ms
  mongodb-prebuilt bin path: /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/ +2ms
  mongodb-prebuilt error from lstat: +0ms { [Error: ENOENT: no such file or directory, lstat '/www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/' }
  mongodb-prebuilt version 3.2.0 is not installed +19ms
  mongodb-prebuilt installing version: 3.2.0 +1ms
  mongodb-download selected platform linux +0ms
  mongodb-download selected architecture i686 +1ms
  mongodb-download selected version: 3.2.0 +0ms
  mongodb-download selected archive tgz +0ms
  mongodb-download final name: mongodb-linux-i686-3.2.0.tgz +0ms
  mongodb-download final download URI: https://fastdl.mongodb.org/linux/mongodb-linux-i686-3.2.0.tgz +1ms
  mongodb-download download directory: /tmp +0ms
  mongodb-download download complete path: /tmp/mongodb-download/mongodb-linux-i686-3.2.0.tgz +0ms
  1) "before all" hook
  mocha:runner finished running +2s

  0 passing (2s)
  1 failing

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.




  mocha:runner end +2ms
  mongodb Shutting down +2s
```

**Mockgoose's npm test when MongoDB package is partially decompressed and test runs.** This is partial output since this goes on forever. In this case, mongod executable is missing.

```
Mockgoose attempting to start server on port: 27025 +1ms
  mongodb-prebuilt bin path: /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/ +0ms
  mongodb-prebuilt spawn +0ms /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27025 --dbpath /www/data/Mockgoose/.mongooseTempDB/27025
  mongodb-prebuilt Failed to start child process. +1ms { [Error: spawn /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod',
  path: '/www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod',
  spawnargs:
   [ '--storageEngine',
     'ephemeralForTest',
     '--port',
     27025,
     '--dbpath',
     '/www/data/Mockgoose/.mongooseTempDB/27025' ] }
  Mockgoose attempting to start server on port: 27026 +4ms
  mongodb-prebuilt bin path: /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/ +1ms
  mongodb-prebuilt spawn +0ms /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27026 --dbpath /www/data/Mockgoose/.mongooseTempDB/27026
  mongodb-prebuilt Failed to start child process. +1ms { [Error: spawn /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod',
  path: '/www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod',
  spawnargs:
   [ '--storageEngine',
     'ephemeralForTest',
     '--port',
     27026,
     '--dbpath',
     '/www/data/Mockgoose/.mongooseTempDB/27026' ] }
  Mockgoose attempting to start server on port: 27027 +1ms
(node) warning: possible EventEmitter memory leak detected. 11 mongoStarted listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at EventEmitter.once (events.js:265:8)
    at Object.start_server (/www/data/Mockgoose/node_modules/mongodb-prebuilt/index.js:27:10)
    at start_server (/www/data/Mockgoose/Mockgoose.js:92:33)
    at /www/data/Mockgoose/Mockgoose.js:97:17
    at ChildProcess.<anonymous> (/www/data/Mockgoose/node_modules/mongodb-prebuilt/index.js:52:5)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
  mongodb-prebuilt bin path: /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/ +3ms
  mongodb-prebuilt spawn +0ms /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27027 --dbpath /www/data/Mockgoose/.mongooseTempDB/27027
(node) warning: possible EventEmitter memory leak detected. 11 mongoShutdown listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at EventEmitter.once (events.js:265:8)
    at start (/www/data/Mockgoose/node_modules/mongodb-prebuilt/index.js:62:11)
    at Object.start_server (/www/data/Mockgoose/node_modules/mongodb-prebuilt/index.js:44:3)
    at start_server (/www/data/Mockgoose/Mockgoose.js:92:33)
    at /www/data/Mockgoose/Mockgoose.js:97:17
    at ChildProcess.<anonymous> (/www/data/Mockgoose/node_modules/mongodb-prebuilt/index.js:52:5)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
  mongodb-prebuilt Failed to start child process. +3ms { [Error: spawn /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod',
  path: '/www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod',
  spawnargs:
   [ '--storageEngine',
     'ephemeralForTest',
     '--port',
     27027,
     '--dbpath',
     '/www/data/Mockgoose/.mongooseTempDB/27027' ] }
  Mockgoose attempting to start server on port: 27028 +1ms
  mongodb-prebuilt bin path: /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/ +0ms
  mongodb-prebuilt spawn +0ms /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27028 --dbpath /www/data/Mockgoose/.mongooseTempDB/27028
  mongodb-prebuilt Failed to start child process. +2ms { [Error: spawn /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod',
  path: '/www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod',
  spawnargs:
   [ '--storageEngine',
     'ephemeralForTest',
     '--port',
     27028,
     '--dbpath',
     '/www/data/Mockgoose/.mongooseTempDB/27028' ] }
  Mockgoose attempting to start server on port: 27029 +1ms
  mongodb-prebuilt bin path: /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/ +0ms
  mongodb-prebuilt spawn +1ms /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27029 --dbpath /www/data/Mockgoose/.mongooseTempDB/27029
  mongodb-prebuilt Failed to start child process. +1ms { [Error: spawn /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod',
  path: '/www/data/Mockgoose/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod',
  spawnargs:
   [ '--storageEngine',
     'ephemeralForTest',
     '--port',
     27029,
     '--dbpath',
     '/www/data/Mockgoose/.mongooseTempDB/27029' ] }
^CTerminated
```

**Comment by winfinit** [comment]
please upgrade to most recent release, there is a breaking api change in 6.0.0, but after upgrade it would give me ability to address tons of quirkiness that people are being reporting.

**Comment by divya48** [comment]
Can somebody please help me in removing the unnecessary logs as below:
2017-12-06T06:39:50.723Z mocha:suite bail undefined
2017-12-06T06:39:50.725Z mocha:suite enableTimeouts true
2017-12-06T06:39:50.733Z mocha:suite bail undefined
2017-12-06T06:39:51.048Z mocha:suite timeout 2000
2017-12-06T06:39:51.048Z mocha:suite retries -1
2017-12-06T06:39:51.048Z mocha:suite enableTimeouts true
2017-12-06T06:39:51.049Z mocha:suite slow 75
2017-12-06T06:39:51.049Z mocha:suite bail undefined
2017-12-06T06:39:51.049Z mocha:suite timeout 2000
2017-12-06T06:39:51.049Z mocha:suite retries -1
2017-12-06T06:39:51.049Z mocha:suite enableTimeouts true
2017-12-06T06:39:51.049Z mocha:suite slow 75
2017-12-06T06:39:51.049Z mocha:suite bail undefined
2017-12-06T06:39:51.050Z mocha:runnable timeout 2000
2017-12-06T06:39:51.050Z mocha:runnable enableTimeouts true
2017-12-06T06:39:51.050Z mocha:runnable timeout 75
2017-12-06T06:39:51.051Z mocha:suite timeout 2000
2017-12-06T06:39:51.051Z mocha:suite retries -1
2017-12-06T06:39:51.051Z mocha:suite enableTimeouts true
2017-12-06T06:39:51.051Z mocha:suite slow 75
2017-12-06T06:39:51.051Z mocha:suite bail undefined
2017-12-06T06:39:51.051Z mocha:runnable timeout 2000
2017-12-06T06:39:51.051Z mocha:runnable enableTimeouts true
2017-12-06T06:39:51.051Z mocha:runnable timeout 75
2017-12-06T06:39:51.056Z mocha:runner grep /.*/
2017-12-06T06:39:51.057Z mocha:runner globals ["DTRACE_NET_SERVER_CONNECTION","DTRACE_NET_STREAM_END","DTRACE_HTTP_SERVER_REQUEST","DTRACE_HTTP_SERVER_RESPONSE","DTRACE_HTTP_CLIENT_REQUEST","DTRACE_HTTP_CLIENT_RESPONSE","COUNTER_NET_SERVER_CONNECTION","COUNTER_NET_SERVER_CONNECTION_CLOSE","COUNTER_HTTP_SERVER_REQUEST","COUNTER_HTTP_SERVER_RESPONSE","COUNTER_HTTP_CLIENT_REQUEST","COUNTER_HTTP_CLIENT_RESPONSE","global","process","Buffer","clearImmediate","clearInterval","clearTimeout","setImmediate","setInterval","setTimeout","console","before","after","beforeEach","afterEach","run","context","describe","xcontext","xdescribe","specify","it","xspecify","xit","XMLHttpRequest","Date"]
2017-12-06T06:39:51.059Z mocha:runner globals []
2017-12-06T06:39:51.059Z mocha:runner start

2017-12-06T06:39:51.061Z mocha:runner run suite

2017-12-06T06:39:51.063Z mocha:runner run suite Stage APIs
  Stage APIs
2017-12-06T06:39:51.064Z mocha:runner run suite Stage APIs Get /stage/getStages without authorization token
    Get /stage/getStages without authorization token
2017-12-06T06:39:51.082Z superagent GET http://localhost:8088/service/stage/getStages
2017-12-06T06:39:51.131Z superagent GET http://localhost:8088/service/stage/getStages -> 200
      √ Should return a success code 2013 (78ms)
2017-12-06T06:39:51.146Z mocha:runner run suite Stage APIs Get /stage/getStages with incorrect authorization token
    Get /stage/getStages with incorrect authorization token
2017-12-06T06:39:51.152Z superagent GET http://localhost:8088/service/stage/getStages
2017-12-06T06:39:51.201Z superagent GET http://localhost:8088/service/stage/getStages -> 401
      √ Should return a success code 2015 (58ms)

2017-12-06T06:39:51.205Z mocha:runner finished running

  2 passing (146ms)

2017-12-06T06:39:51.206Z mocha:runner end

Even though my tests are passing everytime is get a heap of unwanted logs. Quick reply would be highly appreciated 
Please find my package.js code:

{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "mocha"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "async": "^2.6.0",
    "body-parser": "^1.18.2",
    "bookshelf": "^0.10.4",
    "bunyan": "^1.8.12",
    "chai": "^4.1.2",
    "crypto-js": "^3.1.9-1",
    "dateformat": "^3.0.2",
    "express": "^4.16.2",  
    "fs": "0.0.1-security",
    "helmet": "^3.9.0",
    "jsonwebtoken": "^8.1.0",
    "knex": "^0.13.0",
    "mocha": "^4.0.1",
    "moment": "^2.19.1",
    "morgan": "^1.9.0",
    "multer": "^1.3.0",
    "mysql": "^2.15.0",
    "node-uuid": "^1.4.8",
    "node-xlsx": "^0.11.2",
    "nodemon": "^1.12.1",
    "path": "^0.12.7",
    "request": "^2.83.0",
    "supertest": "^3.0.0",
    "underscore": "^1.8.3",
    "xls-to-json-lc": "^0.3.4",
    "xlsx-to-json-lc": "^0.5.0"
  },
  "devDependencies": {
    "chai": "^4.1.2",
    "mocha": "^4.0.1",
    "should": "^13.1.3"
  }
}

test file:
const assert = require('chai').assert;
var supertest = require("supertest");
var should = require("should");
var url = 'http://localhost:8088/service'
var server = supertest.agent(url);
var request = require('supertest');
var base = {'Authorization': 'Bearer ja2RuczM3UjgwUW1waVpOOUtxTzBPUSIsImtpZCI6InNFa01ja2RuczM3UjgwUW1waVpOOUtxTzBPUSJ9.eyJjbGllbnRfaWQiOiI3MTU1Lm5ld2l0ZXhwZXJ0LndlYiIsInNjb3BlIjoidXNlcl9wcm9maWxlIiwic3ViIjoiZHJhdnlhLnNoYWhAYWNjZW50dXJlLmNvbSIsImFtciI6ImV4dGVybmFsIiwiYXV0aF90aW1lIjoxNTEyMTAzNzAwLCJpZHAiOiJlc29fbWZhIiwidXBuIjoiZHJhdnlhLnNoYWhAYWNjZW50dXJlLmNvbSIsImVtYWlsIjoiZHJhdnlhLnNoYWhAYWNjZW50dXJlLmNvbSIsInNhbWFjY291bnRfbmFtZSI6ImRyYXZ5YS5zaGFoIiwicGVvcGxla2V5IjoiMTM5MzUzNiIsInBlcnNvbm5lbG5iciI6IjExMjc5ODg4IiwiZ2l2ZW5fbmFtZSI6IkRyYXZ5YSIsInNuIjoiU2hhaCIsImlzcyI6InVybjpmZWRlcmF0aW9uOmFjY2VudHVyZSIsImF1ZCI6InVybjpmZWRlcmF0aW9uOmFjY2VudHVyZS9yZXNvdXJjZXMiLCJleHAiOjE1MTIxMTgxMjQsIm5iZiI6MTUxMjExNDUyNH0.m6DL97mM_wSzVw9URTyXu_OzxfsJARypRmo3ill1UBAU5Y7n4StixU-JvGXUuug3t8LLFSIIrLamavGD7u5pPG6E8Onk-BCBa4LxLMBJaHfcFGq_XfWtQ-mENX6-3Hnv8uwLngQh1MFLo2Xi-nSPkCf9vpOAKiBF3v0X8eYIZ3las5oxLKSw3ZB69iPKTvgh_KSTTdAuFywX_WdEShJMMqPeydTneQUf8Ey-IpL9q0bzhNN3U8xeOMxgLjb9QGaebufYzpq1dKlV6Hwm_asgg1mDrWmD7KOkQwHJp7eVCchtpINmh7-I4JJIA6jaXP8xE32Iu_Rt_xWM-Gamqt3KrQ'};

describe('Stage APIs', function(){
	describe('Get /stage/getStages without authorization token', function(){
		it("Should return a success code 2013", function(done){
			server
            .get('/stage/getStages')
			.expect(2013)
			.expect('Content-Type', /json/)
			.end(function(err,res){
                res.body.status.should.equal(2013);
                res.body.message.should.equal('Token should be in \"Bearer <generated token>\" format');
				done();
			});
		});
    });
});
