### ISSUE TITLE
Allow override of mongodb version of mongodb-download entirely

### ISSUE THREAD

**Issue by antony** [mccormicka/Mockgoose#177]
Hi,

I'm on Ubuntu 15.04 for which a package is unfortunately not explicitly downloadable from the mongodb site.

I have two options with regards to mongodb-download therefore:

1. Override the version in use to be simply 'linux' rather than Ubuntu
2. Tell Mockgoose not to use mongodb-download but to use my native mongo install

Number two is preferable I think, because I already have mongo installed via apt-get, but I like the fact that mongoose runs an 'in memory' db.

Number one I can't do because I can't get access to mongodb-download from outiside the module.

I can't see any of these options being possible right now, is it something you'd consider implementing?

**Comment by winfinit** [comment]
@antony i've set myself up with 15.04 also, and saw that mongodb works fine with a build for 14.04, so i've just added exception for 15.x release, and it seems to do a trick, please let me know if it is going to work fine for you:

mockgoose@5.2.4

**Comment by antony** [comment]
Thanks roman! I'll give it a go on Monday :)

**Comment by winfinit** [comment]
@antony was this resolved, or you are still having an issue?

**Comment by antony** [comment]
Sorry roman, I've been tasked to deliver a product by March so I've
literally not had a spare minute to check.

Feel free to close the issue, I'll reopen if it still occurs.
Thanks,
Antony
