### ISSUE TITLE
beforeEach and mockgoose.reset issue

### ISSUE THREAD

**Issue by root-io** [mccormicka/Mockgoose#179]
```
beforeEach(function(done) {
  mockgoose.reset(function() {
    done();
  });
});
```
My collections don't seem to be removed

nodejs 4.2.6
mongodb 3.2.1
mongoose 4.3.7
mockgoose 5.2.4

**Comment by rsignavong** [comment]
+1, with the same stack.

My collections aren't empty too, and documents are stored inside mongodb and not using in-memory even if isMocked is set to true.

**Comment by ndinh** [comment]
I am also having the same issue where the mockgoose.reset function is not properly reseting the collections. I have double checked that isMocked is set to be true. I don't know if it matter but I am using a mongoose model for my database, that is stored in a separate location that the index file I am testing. The way I am using mockgoose is very similar to this tutorial: 

http://justincalleja.com/2014/12/14/to-mock-a-mongoose/

**Comment by SkateFreak** [comment]
+1 same issue

**Comment by winfinit** [comment]
try 5.3.2, this should be resolved.

**Comment by root-io** [comment]
I upgrade to 5.3.2, I got this:

```
"before each" hook for "should ...":
TypeError: Cannot read property 'dropDatabase' of undefined
at Function.module.exports.reset (node_modules/mockgoose/Mockgoose.js:180:31)
```

**Comment by winfinit** [comment]
@root-io what version of mongoose are you using?

**Comment by root-io** [comment]
mongoose v4.3.7

**Comment by SkateFreak** [comment]
it works for me after update.

    "mongoose": "^4.3.7",
    "mockgoose": "^5.3.2",

**Comment by winfinit** [comment]
@root-io is it possible for you to share your structure? it maybe because connection was not established yet, are you waiting for connection to complete in "before" hook?

**Comment by SkateFreak** [comment]
this might help. i just discovered that the order of the commands is crucial. this is my setup:

    import mockgoose from 'mockgoose'
    import mongoose from 'mongoose'

    mockgoose(mongoose);

    var app = require('../server/server');
    var request = require('supertest');
    var req = request(app);

    after(function (done) {
        mockgoose.reset();
        mongoose.unmock(function () {
            done();
        });
    });

**Comment by SkateFreak** [comment]
@rsignavong i had the same problem. i discovered that the order of the commands matters.

here is my setup:

    import mockgoose from 'mockgoose'
    import mongoose from 'mongoose'
    
    mockgoose(mongoose);
    
    var app = require('../server/server');
    var request = require('supertest');
    var req = request(app);
    
    after(function (done) {
        mockgoose.reset();
        mongoose.unmock(function () {
            done();
        });
    });
    
    describe('...', function () {
        it('...', function (done) {
            request(app)
                .get('...')
                .end(function (err, res) {
                    if (err) return done(err);
    
                    ...expect...
    
                    done();
                });
        });
    });

**Comment by winfinit** [comment]
is this still an issue with 6.0.0?

**Comment by winfinit** [comment]
please reopen this issue, if you are still experiencing it with release 6

**Comment by piyushbeli** [comment]
@winfinit , I am still having this issue. Can you please confirm if mongodb needs to be running to run the tests ? I guess that is the whole purpose of this library to not to run the mongodb for unit tests. I did not get a good resource to use this (may be my bad).  
I am using latest version of mongoose and mockoose.
"mockgoose": "^6.0.8",
"mongoose": "4.6.0"

Any help will be highly appreciated.

Many thanks
Piyush

**Comment by SkateFreak** [comment]
@piyushbeli here is my working setup. hope it helps

**app.js**

	const _TEST_ = process.env.NODE_ENV == 'test';
	
	import {db, port} from './config'
	import express from 'express'
	import mongoose from 'mongoose'
	
	export const app = express();
	
	if (_TEST_) {
	    const mockgoose = require('mockgoose');
	    mockgoose(mongoose);
	}
	
	mongoose.connect(db[app.get('env')]);
	
	app.listen(port, function () {
	    console.log('server running');
	});


**test.js**

	import {app} from './index'
	import User from './models/user'
	
	after(function (done) {
	    mockgoose.reset(function () {
	        done();
	    });
	});
	
	describe('test', function () {
	    it('should', function (done) {
	        User.create({ /* user data */ });
	    });
	});

you could also use ```supertest``` to mock api requests

**Comment by winfinit** [comment]
@piyushbeli you do not need to start mongod, Mockgoose will start that by itself, its own instance to support your test.

@SkateFreak you need to wait for mockgoose to establish its temporary storage, which can take few seconds, so you have to wait for a callback or a promise. 

mocha and chai example:

```javascript
var should = require('chai').should()
,expect = require('chai').expect
, Mongoose = require('mongoose').Mongoose
, mongoose = new Mongoose
, mockgoose = require('mockgoose')
, Cat = mongoose.model('Cat', { name: String });

describe('User functions', function() {
    before(function(done) {
                mockgoose(mongoose).then(function() {
                    mongoose.connect('mongodb://AnyDatabase.example.com/TestingDB', function(err) {
                        done(err);
                    });
                });
    });

    it("isMocked", function(done) {
                expect(mongoose.isMocked).to.be.true;
                done();
    });

    it("should create a cat foo", function(done) {
                Cat.create({name: "foo"}, function(err, cat) {
                    expect(err).to.be.falsy;
                    done(err);
                });
    });
});
```

**Comment by SkateFreak** [comment]
i haven't encountered any problems yet but thank you for your attention
