### ISSUE TITLE
Mockgoose connection doesn't close if any test case fails

### ISSUE THREAD

**Issue by jhyland87** [mccormicka/Mockgoose#190]
I'm creating some unit tests for my Mongoose models using Lab and Mockgoose, and I'm having the DB connection opened via Labs `lab.before()` method, then the database connection killed in labs `lab.after()` method. The problem I'm running into, is if any test cases fail, then the connection won't close, but the `lab.after()` **does** get executed (I added some console output for debugging)

```javascript
    const mongoose = require('mongoose')
    const mockgoose = require('mockgoose')
    const appRoot = require('app-root-path')
    
    mockgoose( mongoose )
    
    // Create the mongoose connection on init
    before(function(done) {
        mongoose.connect('mongodb://example.com/TestingDB', function(err) {
            done(err)
        })
    })
    
    // Close the fake connection after all tests are done
    after(function(done) {
        console.log('Closing') // Shows in console (always)
        mongoose.connection.close(function() {
            console.log('Closed') // Also. always shows in console
            done()
        })
    })
    
    const Models = appRoot.require('./dist/models')(mongoose)
    
    describe('Foobar', function () {
        describe('.createFoo', function () {
            it( 'Creating foo with no data', function( done ) {
                
                // Executing Foobar.createFoo with an empty object WILL populate err
                Models.Foobar.createFoo( { /* Some Data.. */ }, ( err, data ) => {
                    // This will fail the test case, since err will contain an error..
                    expect( err ).to.not.equal( null )
                    done()
                } )
            })
        })
    })
```
So if I change the:
```javascript
expect( err ).to.not.equal( null )
```
to:
```javascript
expect( err ).to.equal( null )
```
Then it works perfectly fine. But if I simulate a test case failing, then both the "**Closing**" and "**Closed**" show up in the console, but the connection itself never closes... It just hangs there until I hit ctrl+c

I looked through the running processes to see if there was a processing hanging when the test case failed:
```
$ ps aux |grep -i [m]ongo
myuser          3666   0.0  0.5  3054308  19176 s003  S+    2:27PM   0:00.08 node /Users/me/my_project/node_modules/mongodb-prebuilt/binjs/mongokiller.js 3608 3663
```

Is this a bug? or did I forget to do something in the unit test?

**Comment by winfinit** [comment]
@jhyland87 make sure you are using mockgoose 5.3.0, that will ensure that mongod processes are not left behind, it may take couple of seconds for them to get killed, but they all should get killed.

i see that there is a bug with close, i will check that out, for now however, i would recommend just removing your "after" hook, and don't close a connection, that should do a trick, here is what i've tried:

```javascript
const mongoose = require('mongoose')
const mockgoose = require('mockgoose')
mockgoose( mongoose )

before(function(done) {
    mongoose.connect('mongodb://example.com/TestingDB', function(err) {
        done(err)
    })  
});

describe('Foobar', function () {
    describe('.createFoo', function () {
        it( 'Creating foo with no data', function( done ) { 
            expect( null ).to.not.equal( null );
            done();
        })  
    }); 
});
```

that will leave mongod for a second or two after test is done, but mockgoose will take care of that

**Comment by winfinit** [comment]
published mockgoose@5.3.2 that will address disconnect bug

**Comment by jhyland87** [comment]
Looked like upgrading from 5.2.4 to 5.3.0 worked! Thank you

**Comment by jhyland87** [comment]
Upgrading did however break something else though :( Created a ticket for it -> https://github.com/mccormicka/Mockgoose/issues/192
