### ISSUE TITLE
Mockgoose persistence between cases

### ISSUE THREAD

**Issue by Lightheaded** [mccormicka/Mockgoose#191]
Hello! I am trying to test my REST API with the help of mockgoose. Although it seems that I am doing something wrong. It seems that the item created in my first describe() doesn't live to be retrieved in the second describe(). Is that by design, or the mockgoose entries are not only not persistant to the suite but between describe() blocks too?

```javascript
  describe('POST /', function() {
    it('should create a training', function(done) {
      api.post('/')
        .send({
          user_id: 1,
          name: 'Training name',
          ...
        })
        .expect(200)
        .end(function(err, res) {
          if (err) return done(err);
          expect(err).to.equal(null);
          expect(res.body.trainingId).to.be.a('string');
          done();
        });
    });
  });
  describe('GET /', function() {
    it('should return at least one training', function(done) {
      api.get('/')
        .set('Accept', 'application/json')
        .expect(200)
        .end(function(err, res) {
          console.log(mongoose.isMocked);
          expect(res.body).to.have.length.at.least(1);
          done();
        });
    });
});
```

**Comment by winfinit** [comment]
it should persist between describe blocks, unless there is a disconnect/close issued and/or reset. I will check it out.

**Comment by Lightheaded** [comment]
Hey! Any progress? I haven't managed to get it working :(

**Comment by winfinit** [comment]
did some work today on mockgoose, there is an API change in 6.0.0 release, but it is minor, can you please let me know if that is working for you?

**Comment by Lightheaded** [comment]
Yes, it works after the update to 6.0.0. Thanks a lot!
