### ISSUE TITLE
Upgrading Mockgoose from 5.2.4 to 5.3.0 breaks schema items 'unique' setting

### ISSUE THREAD

**Issue by jhyland87** [mccormicka/Mockgoose#192]
I have a Mongoose schema item which has `unique: true`, and a unit test that verifies the unique value requirement worked when I was using Mockgoose@5.2.4. However, I just upgraded to Mockgoose@5.3.0, and noticed that that specific test case was failing (meaning it was able to create a document **with** a duplicate value, instead of failing).

I did make some changes after the upgrade, so to verify that it was the upgrade itself that broke the test case, I downgraded from Mockgoose@5.3.0 to Mockgoose@5.2.4, and the unit test failed

Heres the schema (with just the relevant schema item)

```
const modelSchema = new Schema({
    name: {
        type: Schema.Types.String,
        trim: true,
        select: true,
        unique: true,
        required: true,
        minlength: 4,
        maxlength: 30
    }
})
```

Heres the test case:

```
it( 'Creating a document with a duplicate name', function( done ) {
    Mymodel.createDoc( { name: 'Foo Bar Baz' }, ( err1, data1 ) => {
        expect( err1 ).to.equal( null )

        Mymodel.createDoc( { name: 'Foo Bar Baz' }, ( err2, data2 ) => {
            expect( err2 ).to.not.equal( null )
            done()
        } )
    } )
})
```

The above snippets are just the relevant parts of the schema and the unit test, but if you need anything more, just let me know (But there isn't much to it, im just creating a doc with duplicate values)

Is this a bug? Or am I doing something wrong.

**Comment by winfinit** [comment]
@jhyland87 I don't understand how this would be affected, because it is a database function, mockgoose itself doesnt mess with indexes or constraints.

is it possible for you to put a standalone test for me showing your issue?

**Comment by whollacsek** [comment]
hi @winfinit, I'm having the same issue here.

This also happens when setting the schema index like this `schema.index({field: 1}, {unique: true});`

I'm using `"mockgoose": "^5.3.3"` and `"mongoose": "^4.4.6"`.

**Comment by winfinit** [comment]
can someone please provide a complete test that i can just paste and see a failure?

**Comment by winfinit** [comment]
is this still an issue?

**Comment by JoelKlint** [comment]
I encountered the same problem yesterday. I solved it by not calling mockgoose.reset() in my test teardowns. It seems like reset() is breaking the unique index in some way.

Bad:
```js
after(function(done) {
    mockgoose.reset(function() {
        done()
    })
})
```

Good:
```js
after(function(done) {
    Model.remove({}).then(function() {
        done()
    })
})
```

I have recreated the error in this repo:
https://github.com/JoelKlint/mockgoose-problem

**Comment by winfinit** [comment]
@JoelKlint that is correct, reset drops every database, it bring it back to "clean" condition, so that would remove indexes also

**Comment by diegohaz** [comment]
I also ran into this issue. Maybe `mockgoose.reset` could have an option to drop the collections but keep the database with its indexes.

**Comment by winfinit** [comment]
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release
