### ISSUE TITLE
Server Sockets Closed

### ISSUE THREAD

**Issue by halleycarleton** [mccormicka/Mockgoose#194]
I'm trying to use mockgoose but when I try to create a document I get the error "server localhost:27018 sockets closed".

Here is a simple example to recreate the issue:

```js
'use strict';

var mongoose    = require('mongoose');
var mockgoose   = require('mockgoose');
var Schema      = mongoose.Schema;
var BunnySchema = new Schema({
	name: String,
	color: String,
	timestamp: {
		type: Date,
		default: Date.now
	}
});
var Bunny = mongoose.model('Bunny', BunnySchema);

mockgoose(mongoose);
mongoose.connect('mongodb://localhost/testDB');

Bunny.create({name: 'foo', color: 'white'}, function(err) {
	console.log(err);
});
```

This works fine if I remove mockgoose.

If I try to find a document with mockgoose I get no errors.
```js
Bunny.findOne({name: 'foo'}, 'color timestamp', function(err, data) {
	console.log(err, data);
});

// null null
```

**Comment by winfinit** [comment]
@halleycarleton it looks like you are not waiting for a connection to actually establish, and although it possibly would work with mongoose, and running mongodb, you still have a race condition in your code. it would be appropriate to wait for a connection to actually get established first, so something like this:

```javascript
mockgoose(mongoose);
mongoose.connect('mongodb://localhost/testDB', function(err) {
   Bunny.create({name: 'foo', color: 'white'}, function(err) {
       console.log(err);
   });
});


```

**Comment by winfinit** [comment]
@halleycarleton I didn't see your response, I am closing this issue.
