### ISSUE TITLE
createConnection is not return the connection

### ISSUE THREAD

**Issue by omri-shaiko** [mccormicka/Mockgoose#195]
Mongoose return the connection when i use it like this:
var conn = mongoose.createConnection('mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]', options); (from http://mongoosejs.com/docs/connections.html)

But mockgoose don't return the connection at all. Why is that? and how can i get it?

Tnx

**Comment by akoskm** [comment]
I can confirm this. If I call `mongoose.createConnection` on a mongoose object that was previously `mockgoose(mongoose)`, `createConnection` returns undefined.

**Comment by omri-shaiko** [comment]
See this PR:
https://github.com/mccormicka/Mockgoose/pull/198

**Comment by winfinit** [comment]
resolved in 6.0.1, thank you for reporting this issue.
