### ISSUE TITLE
gruntfile missing?

### ISSUE THREAD

**Issue by zirho** [mccormicka/Mockgoose#199]
Hi, 

I'd like to look into the project.
I tried to install grunt-cli and ran into error saying missing grunt file.

Will you be able to include the grunt file?
Also, you may need to include grunt in dev dependencies.

thanks

**Comment by vdeturckheim** [comment]
What do you need a gruntfile for ?

**Comment by zirho** [comment]
Just to see how this project is managed and try out some features that I want to add.

It's okay if it's too much trouble 

thanks

**Comment by winfinit** [comment]
@zirho I am not using grunt for this project, it consists of a single project file, and single unit test.

**Comment by zirho** [comment]
okay thank you for heads up
