### ISSUE TITLE
mockgoose will eat the error message of  `Error: Cannot find module '../test/util.js' from `require()` in `mocha 2.4.5`

### ISSUE THREAD

**Issue by spontaneous01** [mccormicka/Mockgoose#203]
Hi, 

I found a problem which spend my few hours to figure out what happen.

The versions:
```
Nodejs: 5.9.1
Npm: 3.7.3
Mockgoose: 5.3.3
Mongoose: 4.4.6
Mocha: 2.4.5
```

The problem code:
```
// Lib
var async = require('async');
var chai = require('chai');
var should = chai.should();
var expect = chai.expect();


// Mock MongoDB
var mongoose = require('mongoose');
var mongoObjectId = mongoose.Types.ObjectId;

var mockgoose = require('mockgoose');
mockgoose(mongoose);    // <------------ start mock
var req = require('../test/util.js');  // <------------ should be error when  `utils.js` is not existed. But not.

describe('Test mocha', function() {
   it('should work here', function (done) {
       done();
   }) 
});
```

I was thought that is due to the `ES6 (ES2015)` code in my module firstly. I try `Babel 6` to fix it but I was wrong.

This is it will be like: After running `mocha` or `mocha --recursive` (when the problem code is in the sub folders), the terminal returns immediately **without any error messages**.

Is this a bug? Can it be fix? Thanks.

**Comment by winfinit** [comment]
please upgrade to most recent release, there is a breaking api change in 6.0.0, but after upgrade it would give me ability to address tons of quirkiness that people are being reporting.
