### ISSUE TITLE
Error running mocha test

### ISSUE THREAD

**Issue by bhushanvadgave** [mccormicka/Mockgoose#218]
Ran below test

```
var Mongoose = require('mongoose').Mongoose;
var mongoose = new Mongoose();

var mockgoose = require('mockgoose');

before(function(done) {
    mockgoose(mongoose).then(function() {
        mongoose.connect('mongodb://example.com/TestingDB', function(err) {
            done(err);
        });
    });
});

describe('...', function() {
    it("...", function(done) {
        // ...
        done();
    });
});
```

And I get below error

`Uncaught TypeError: bin_path is not a function`

After doing some debugging I found that `install.js` script in `mongodb-prebuilt` npm package is supposed to create `dist` directory under `mongodb-prebuilt` but it is not.

I am using npm 3.9.2.
Need help.

**Comment by raphaelokon** [comment]
Same here.

**Comment by schweigerd** [comment]
I get the same error. Creating the dist directory did not help.
Mockgoose 6.0.3

**Comment by petershaw** [comment]
On my local maschine everything workes fine and all tests are running. On my jenkins i get;

    1) Application Add "before all" hook:
     Uncaught TypeError: bin_path is not a function
      at install (node_modules/mockgoose/node_modules/mongodb-prebuilt/index.js:155:20)
      at Object.start_server (node_modules/mockgoose/node_modules/mongodb-prebuilt/index.js:57:16)
      at node_modules/mockgoose/Mockgoose.js:144:42
      at next (node_modules/mockgoose/node_modules/rimraf/rimraf.js:74:7)
      at CB (node_modules/mockgoose/node_modules/rimraf/rimraf.js:110:9)
      at node_modules/mockgoose/node_modules/rimraf/rimraf.js:136:14
      at FSReqWrap.oncomplete (fs.js:82:15)


(Jenkins) node:
v4.5.0

(Local Mac) node
v6.3.1

Did anyone found a reason for that bin_path thing?

**Comment by jdormit** [comment]
Did anyone find a solution to this?

**Comment by jimjkelly** [comment]
> Then I found the solution: I installed mongo an then i reinstall the modules. Everything works fine now.

Can you expand a bit on this?  Do you mean install an actual mongodb database on the same host?  That seems a bit excessive... hoping not.

**Comment by felipeclopes** [comment]
I'm still facing this issue inside my Node docker container.

```
root@13a7bb4f04bb:/app# npm list mockgoose
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.1
`-- mockgoose@6.0.8 

npm info ok 
root@13a7bb4f04bb:/app# npm list mongoose 
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.1
`-- mongoose@4.5.9 

npm info ok 
root@13a7bb4f04bb:/app# npm list mongodb-prebuilt
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.1
`-- mockgoose@6.0.8
`-- mongodb-prebuilt@5.0.6 
```

Does anyone have the real solution?

**Comment by winfinit** [comment]
what OSes are you using? my guess is that install failed because mongodb didnt have a package, or prebuilt couldn't map release to correct mongodb.

**Comment by hlandao** [comment]
Same here and looks like an issue with the version of NodeJS.

**Comment by winfinit** [comment]
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release

**Comment by lucaslago** [comment]
@felipeclopes I was facing the same issue while running my tests on docker containers. 

I was replacing /node_modules/mongodb-prebuilt directory inside the test container with host node_modules dependencies so it couldn't find the path to the container's mongodb-prebuilt binaries during tests.

mongodb-prebuilt is a compiled dependency and cannot be copied over.
