### ISSUE TITLE
unmock not working when using createConnection

### ISSUE THREAD

**Issue by grimabe** [mccormicka/Mockgoose#219]
Hi,

I am creating two connections with the **createConnection** method from mongoose.

But when I tried to use the **unmock** method, the callback is never called.

I assume this is due to this line : 
**connect_args[0] = orig_connect_uri;** in the following code : 

``` js
    mongoose.unmock = function(callback) {
        mongoose.disconnect(function() {
            delete mongoose.isMocked;
            connect_args[0] = orig_connect_uri;
            mongoose.connect = orig_connect;
            callback();
        });
    };
```

indeed when you create a connection using **createConnection** this code is called : 

``` js
        mongoose.createConnection = function() {
            connect_type = "createConnection";
            createConnection_args = arguments;
            orig_createConnection_uri = createConnection_args[0];
            createConnection_args[0] = mockgoose_uri;
            return orig_createConnection.apply(mongoose, createConnection_args);
        };
```

so the **connect_args** variable is never instantiated. I think the **unmock** function should use both **connect_args** and **createConnection_args**. The same goes for the **orig_connect_uri** and **orig_createConnection_uri**.

I added a try catch around the **unmock** method and I indeed got the following error : 
`TypeError: Cannot set property '0' of undefined`

I am not using the reconnect method but I am pretty sure there is the same problem with the **unmockAndReconnect** method.

**Comment by winfinit** [comment]
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release
