### ISSUE TITLE
Multi instances of mongoose

### ISSUE THREAD

**Issue by conradoqg** [mccormicka/Mockgoose#22]
How to work with multi instances of mongoose? Seems like, if I mock two instances, both will share the same data (db.js). I think if the mockgoose create one data per mongoose or connectionString, they will work better for me.

What do you think?

**Comment by arg20** [comment]
If we use a test engine that runs multiple tests at once, each test should run in an isolated environment. If we could do this I would definitely use mockgoose, hell I'd contribute as much as I can to it.

**Comment by winfinit** [comment]
I believe that 5.x would allow you to do this, as long as you have separate connect statements, each one would run against own instance. If you could give it a try, or give me more details on how you run and write your test, I can test it, before closing this issue

**Comment by cantremember** [comment]
Mockgoose mocks a specific instance of the Mongoose framework. each mock is backed by an in-memory `mongod` instance with a unique port.  the in-memory db is volatile to the lifespan of the mock, and is port-specific

in theory, if you construct multiple Mongoose instances and mock them independently, Mockgoose will keep them distinct (as a result of its port conflict avoidance logic).  if you mock before, and unmock after, each individual Test Case, you may be able to get the isolation you desire
