### ISSUE TITLE
Project migrated

### ISSUE THREAD

**Issue by winfinit** [mccormicka/Mockgoose#222]
Hello,

I've created a new organization Mockgoose, and now this project is moved under Mockgoose/Mockgoose which will allow me to add more participants, and speedup publishing turn around.

Please report all of the issues under Mockgoose/Mockgoose

**Comment by jaredreich** [comment]
You should have transferred this repo to the new organization to keep its start count!

Nice work on this project BTW

**Comment by sibelius** [comment]
@winfinit can u please use this https://github-issue-mover.appspot.com/ to move all the issues to the new repo?

**Comment by sibelius** [comment]
just adding the link to the new repo: https://github.com/Mockgoose/Mockgoose

to make it easy

**Comment by winfinit** [comment]
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release

**Comment by winfinit** [comment]
(i don't have perms for this project to move...)
