### ISSUE TITLE
Mockgoose can not install due to issue with mongodb_prebuilt

### ISSUE THREAD

**Issue by ohmyjersh** [mccormicka/Mockgoose#225]
./node_modules/mongodb-prebuilt

> node install.js

module.js:457
    throw err;
    ^

Error: Cannot find module '../filterSince'

**Comment by gil0mendes** [comment]
I have the same issue here, I think the pull request #223 can fix this issue. I will test and soon as possible I post the result.

**Comment by gil0mendes** [comment]
I have a solution for you. We don't need the previous mentioned pull request, execute the install in debug mode, like this `DEBUG=* npm install`

On the output message, you can find the temporary folder, and removing that you will be able to download the `.tgz` file again and everything will be perfect 😉

**Comment by winfinit** [comment]
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release
