### ISSUE TITLE
Gives MongoError if mongod is not running locally

### ISSUE THREAD

**Issue by piyushbeli** [mccormicka/Mockgoose#226]
If I stop the mongod process and then try to run the test it exits with MongoError. However on running mongod it does not create an db/collection on mongo database but it looks like it's a hard dependency to run the mongod service to make monkgoose work.
I believe reason behind why it goes and try to connect to the mongo db is the this line
LN: 90: orig_createConnection.apply(mongoose, createConnection_args);
If I comment out this line then mongo error does not come (obviousely because no mongo connection events), but my test case will not run and timeout if I try to fetch something from model.

Can you please help me if I am doing something worng ? I also tried to run the simple test from this repo
https://github.com/justin-calleja/mongoose-blog-template-1
Same issue with this too.

**Comment by winfinit** [comment]
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release
