### ISSUE TITLE
Compound index not working

### ISSUE THREAD

**Issue by xcanchal-uz** [mccormicka/Mockgoose#229]
When trying to test a $text search query testing with mocha and mongoose compound indexes it fails with the next message: " text index required for $text query stack". 

Is compound indexing currently supported in mockgoose? Thanks!

**Comment by winfinit** [comment]
latest version of Mockgoose is actually running latest version of mongodb, so its support is limited to Mongoose and MongoDB itself.

what version of mockgoose are you running?

**Comment by winfinit** [comment]
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release
