### ISSUE TITLE
Subdocuments not returned when using projection with Mockgoose

### ISSUE THREAD

**Issue by shankiesan** [mccormicka/Mockgoose#230]
This could well be a noob issue as it seems similar to #59 (which is marked as resolved)...

I've got a Gym scheme defined with a subdocument schema Lines.

I'm trying to test the following code in my controller:

```
Gym.findOne(
    { "lines._id": req.params._id },
    { "lines.$": 1 })
  .exec((err, gym) => {
    if (err) {
      return res.status(500).send(err);
    }
    if (!gym) {
      return res.sendStatus(404);
    }
    console.log(gym);
    res.json(gym.lines[0]);
  });
```

i.e. I want to try to return a single line by its `_id`. This works fine in my non-mocked code (i.e the `console.log` above returns a gym with the single matched line object); however, when I run this with Mockgoose, I only get the `_id` of the gym.

If I remove the projection `{ "lines.$": 1 }`, I get the entire Gym object with _all_ lines – as is to be expected – both in the production code and using Mockgoose.

I'm not 100% sure that this is a Mockgoose issue – but I think that it's unlikely to be due to my test runner, AVA. Any ideas?

Using 6.0.8...

**Comment by winfinit** [comment]
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release
