### ISSUE TITLE
Support for the aggregation Framework

### ISSUE THREAD

**Issue by nukulb** [mccormicka/Mockgoose#29]
Looking for support for the aggregation framework.
http://docs.mongodb.org/manual/core/aggregation-introduction/
With the aggregation framework comes a huge set awesome operators that make the aggregation framework very useful
an example of an operator can be found here
http://docs.mongodb.org/manual/reference/operator/aggregation/project/
On the side bar of the above link you can find many other operators.

Example product schema
```
var ProductSchema = new Schema({
    name: String,
    attributes: [
        {
            k: String,
            v: String
        }
    ]
});
```
The follow query will return all products that have the name 'dav' in them and return the number of attributes in those products.
```
    var x = new RegExp('dav');
    Product
    .aggregate(
        [
               {
                   $match: { name: {$regex: x}},
                },
                {
                    $unwind: '$attributes'
                },
                {
                    $group: { _id: "$_id", num: { $sum: 1 }}
                },
                {
                    $sort: { num: -1}
                },
                {
                    $limit: 3
                }
        ],
    function (err, products) {
        console.log(products);
        console.log('Read ' + products.length + ' in ');
    });
```

Output
```
[ { _id: 531a2474ed30a70000000010, num: 10 },
  { _id: 531a44c35828f200000000c0, num: 3 } ]
```

**Comment by MLourensMoog** [comment]
+1

**Comment by mansona** [comment]
Has there been any progress on this?

**Comment by freakru** [comment]
+1

**Comment by paambaati** [comment]
+1

**Comment by franky-continu** [comment]
+1

**Comment by napcoder** [comment]
+1

**Comment by alexruzzarin** [comment]
+1

**Comment by tnolf** [comment]
+1

**Comment by mr-e-** [comment]
+1

**Comment by MSchip** [comment]
+1

**Comment by ftairs** [comment]
+1

**Comment by sdburgess** [comment]
+1

**Comment by scullabyte** [comment]
+1

**Comment by winfinit** [comment]
please try out latest release candidate mockgoose@5.0.0-rc.12 this release is using in memory mongodb storage, and supports every mongodb and mongoose operation.

**Comment by winfinit** [comment]
5.0 is now latest
