### ISSUE TITLE
Support duplicate validation on `index: { unique: true} }`

### ISSUE THREAD

**Issue by ydaniv** [mccormicka/Mockgoose#58]
For now Mockgoose requires setting `unique: true` explicitly on the field.
mongod will throw 11000 error for `index: { unique: true} }` but Mockgoose ignores it and test relying on this error occurring will fail.

**Comment by jaseeey** [comment]
Has anyone had any luck with this issue? I'm finding that my unique indexes are being ignored when performing an update() using Mockgoose. The only way around this is using a save() which does throw a duplicate key error, however update() simply updates and allows a duplicate to exist whilst the actual MongoDB throws an error.

**Comment by winfinit** [comment]
5.0 honors indexes

**Comment by jaseeey** [comment]
Thank you for following this up, has this been applied to the latest 5.0rc?
