### ISSUE TITLE
Needs an "unmock" method

### ISSUE THREAD

**Issue by aroman** [mccormicka/Mockgoose#62]
Because Node will only `require` a module once globally in a process instance, when Mockgoose "infects" `mongoose`, it causes *all* future calls to Mongoose to be mocked. This is fine most of the time, but I have a specific (not uncommon) usecase where this is problematic:

My express app has a suite of unit tests (testing Mongoose models) and a suite of integration tests (testing http, controllers, and mongoose). I use mockgoose for the unit tests, but a real Mongo database for the integration tests. Running both tests in the same call to `mocha` will fail because there is no way to tell mockgoose to "unmock" mongoose.

Does this make sense? Am I misunderstanding something? Thanks :)

**Comment by DiegoTUI** [comment]
@aroman I just run into the same problem in the past few days. I am using Jasmine for my tests, and for some tests I needed mongoose mocked while for others I needed the real thing. Here is how I solved it: for the tests that I required mongoose mocked, I did the mocking in the ```beforeAll()```block and then I cleared the require cache for mongoose in the ```afterAll()``` block. This way, when the next test is coming, mongoose is required again, and it's returned unmocked. Like this:
```
describe('my_test' function() {
    var mockgoose = require('mockgoose');
    var mongoose;

    beforeAll(function() {
        var mongoose = require('mongoose');
        mockgoose(mongoose);
    });

    afterAll(function() {
        delete require.cache[require.resolve('mongoose')];
    });

    it('my first spec', function() {
        ...
    });
});
```

**Comment by winfinit** [comment]
added few extra methods in mockgoose@5.1.0, let me know if those would help your use cases

.isMocked
.unmock(callback)
.unmockAndReconnect(callback)
