### ISSUE TITLE
select key in array

### ISSUE THREAD

**Issue by qraynaud** [mccormicka/Mockgoose#70]
I'm having a strange issue with mockgoose.

I write the following mongoose request (in my data model, modules is an array of object):
```js
Model
        .where({ "user_id": userId, "modules.state": "done" })
        .select("id level modules._id modules.status modules.state")
        .exec(/* ... */);
```

And I get back an object looking like this:
```js
{
  "id": "<some_id>",
  "level": 3,
  "modules": [ {} ]
}
```

There are no keys in the objects inside modules. I believe this is a bug in mockgoose because this works properly in mongo / barebone mongoose.

**Comment by winfinit** [comment]
this should be resolved with 5.0 release
