### ISSUE TITLE
update + overwrite

### ISSUE THREAD

**Issue by qraynaud** [mccormicka/Mockgoose#78]
I'm using in my app something like:
```js
var someQuery = {_id: '...'};
var someDoc = {
  attr: 'attr',
  attr2: 'attr2'
};
Model.update(someQuery, someDoc, {upsert: true, overwrite: true});
```

I need it because I get data from an external source that might contain less attributes than the previous data in DB. i want those attributes to be removed. If you don't provide `overwrite: true` to mongoose, it silently convert each call into a `$set` operation. With this option, it does suppress this behaviour.

My problem is that right now, mockgoose is replying:
```
Mockgoose currently does not support the attr operation
Mockgoose currently does not support the attr2 operation
```

**Comment by winfinit** [comment]
this should be resolved with 5.0 release
