### ISSUE TITLE
Mockgoose calls mongoose.createConnection with incorrect arguments

### ISSUE THREAD

**Issue by viking** [mccormicka/Mockgoose#89]
See: https://github.com/mccormicka/Mockgoose/blob/475971400d8a891184df8c95675816434dd2889c/Mockgoose.js#L60

`mongoose.createConnection` requires the first argument to be either a hostname or a URI. Mockgoose is calling it with the database name as the first argument. This causes `connection.host` to return the database name instead of the host name.

This matters because I'm creating multiple connections based on `mongoose.connection.host`.

What are your thoughts?

**Comment by winfinit** [comment]
this should be resolved with 5.0 release
