### ISSUE TITLE
error calling connection.open

### ISSUE THREAD

**Issue by chrisjaure** [mccormicka/Mockgoose#91]
I'm using `mongoose.createConnection()` but I'm not passing any arguments. Later I'm calling `open()` on that connection passing in the host and name. Unfortunately that results in the following error: `Error: Trying to open unclosed connection.`

Since `mongoose.createConnection` just proxies any arguments to `Connection#open` or `Connection#openSet` as described here http://mongoosejs.com/docs/api.html#index_Mongoose-createConnection, would it be possible to intercept those calls instead?

**Comment by winfinit** [comment]
please upgrade to 5.0 release, let me know if you will run into any issues
