### ISSUE TITLE
Support sparse values (specifically sparse nested values)

### ISSUE THREAD

**Issue by gregc** [mccormicka/Mockgoose#92]
When I first ran my tests with Mockgoose, nearly half of them failed (54 or so).

Most of those failures were due to Mockgoose not honoring the `sparse` property on model properties that are `unique` and `sparse`.

I hacked in a fix by redefining `validateOptions()` in Validate.js as follows:

    function validateOptions(type, doc, schema, cb) {  
        var indexes = schema.indexes();
        for (var i = 0, il = indexes.length; i < il; ++i) {
            if(indexes[i][1].unique && indexes[i][1].sparse) {
                var query = createQuery(indexes[i][0], doc);
                var value = query[Object.keys(query)[0]];
                if (value != null) {
                  var results = utils.findModelQuery(db[type], query);
                  if (results.length > 0) {
                      return cb(createError(Object.keys(indexes[i][0]).join(', ')));
                  }
                }
            } else if(indexes[i][1].unique) {
                var query = createQuery(indexes[i][0], doc);
                var results = utils.findModelQuery(db[type], query);
                if (results.length > 0) {
                    return cb(createError(Object.keys(indexes[i][0]).join(', ')));
                }
            }
        }
        return cb(null);
    }

I also noticed that the current version of `createQuery()` in that file did not support nested values.  This is an easy fix:

    function createQuery(fields, doc) {
        var query = {};
        _.forIn(fields, function (value, pathName) {
            query[pathName] = utils.findNestedValue(doc, pathName);
        });
        return query;
    }

Also, `setNestedValue()` in utils.js fails if the intermediate value was undefined beforehand.  That is, sometimes the modelItem variable is set to `undefined`.

After dealing with these issues, I widdled my failing tests down to 7.  I'm not sure what is causing the rest of the failures right now.  I will look at this more later.

Let me know what you think.

**Comment by vanb** [comment]
+1

**Comment by whummer** [comment]
+1

**Comment by winfinit** [comment]
this should not be an issue with 5.0 release
