### ISSUE TITLE
Support for .populate(ref, fields)

### ISSUE THREAD

**Issue by PavelVanecek** [mccormicka/Mockgoose#95]
Mockgoose lacks support of second `populate` param, as described here: http://mongoosejs.com/docs/populate.html section *"Field selection"*.

> What if we only want a few specific fields returned for the populated documents? This can be accomplished by passing the usual field name syntax as the second argument to the populate method:

    Story
    .findOne({ title: /timex/i })
    .populate('_creator', 'name') // only return the Persons name
    .exec(function (err, story) { /* ... */ }

**Comment by winfinit** [comment]
mockgoose took a bit different direction with 5.0 release, this is now supported.
